src/dealership/urls.py
from django.conf.urls import url

from dealership import views

import views.login
import views.chat
from views.overview import *
from views.appointment import *
from views.customers import *
from views.rservices import *
from views.notifications import *
from views.sms_reply import *
from views.manage import *

urlpatterns = [
    #url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^$', views.login.index, name='index'),
    url(r'delete_models', views.manage.delete_models, name='delete_models'),
    url(r'create_models', views.manage.create_models, name='create_models'),
    url(r'select_makes', views.manage.select_makes, name='select_makes'),
    url(r'^login/(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', views.login.loginview, name='login'),
    url(r'^login/$', views.login.loginview, name='login'),
    url(r'^logout/$', views.login.logoutview, name='logout'),
    url(r'^request/$', views.login.requestview, name='request'),
    url(r'^password/change$', views.login.passchange, name='passchange'),
    url(r'^password/create$', views.login.passcreate, name='passcreate'),
    url(r'^password/reset$', views.login.passreset, name='passreset'),
    url(r'^username/reset$', views.login.userreset, name='userreset'),
    url(r'^terms/$', views.login.terms, name='terms'),
    url(r'^firstlogin/$', views.login.firstlogin, name='firstlogin'),
    #chat
    url(r'^chats/$', views.chat.chats, name='chats'),
    url(r'^chat/$', views.chat.chat, name='chat'),

    url(r'^getnotifications/$', views.notifications.get_live_notifications, name='get_notifications'),
    url(r'^resetnotifications/$', views.notifications.reset_live_notifications, name='reset_notifications'),

    url(r'^smsreply/$', views.sms_reply.SMSReply.as_view(), name='sms_reply'),

    #overview
    url(r'^overview/$', views.overview.overview, name='overview'),
    #url(r'^overview/time/daily$', views.overview.ov_time_daily, name='ov_time_daily'),
    url(r'^overview/daily$', views.overview.ov_time_daily, name='ov_time_daily'),
    #url(r'^overview/advisor/daily$', views.overview.ov_adv_daily, name='ov_adv_daily'),
    #url(r'^overview/status/daily$', views.overview.ov_status_daily, name='ov_status_daily'),
    #url(r'^overview/time/weekly$', views.overview.ov_time_weekly, name='ov_time_weekly'),
    url(r'^overview/weekly$', views.overview.ov_time_weekly, name='ov_time_weekly'),
    #url(r'^overview/advisor/weekly$', views.overview.ov_adv_weekly, name='ov_adv_weekly'),
    #url(r'^overview/status/weekly$', views.overview.ov_status_weekly, name='ov_status_weekly'),
    #overview_ajax
    url(r'^overview/wallboard$', views.overview.wallboard_ajax_view, name='wallboard'),
    url(r'^overview/searchcustomer$', views.overview.searchcustomer_ajax_view, name='searchcustomer'),
    url(r'^overview/time/daily/slab$', views.overview.dailyapt_ajax_view, name='ov_time_daily_slab'),
    url(r'^overview/time/daily/search$', views.overview.time_daily_search_ajax_view, name='ov_time_daily_search'),
    url(r'^overview/time/daily/appt$', views.overview.time_daily_search_appt_ajax_view, name='ov_time_daily_search_appt'),
    url(r'^overview/time/daily/row$', views.overview.appointment_row_ajax_view, name='ov_time_daily_row'),
    url(r'^overview/time/weekly/day$', views.overview.time_weekly_day_ajax_view, name='ov_time_weekly_day'),
    url(r'^overview/time/weekly/slab$', views.overview.time_weekly_slab_ajax_view, name='ov_time_weekly_slab'),
    url(r'^overview/daily/advisor$', views.overview.advisor_ajax_view, name='ov_daily_advisor'),
    url(r'^overview/daily/advisor/slab$', views.overview.advisor_daily_slab_ajax_view, name='ov_advisor_daily_slab'),
    url(r'^overview/weekly/advisor/slab$', views.overview.advisor_weekly_slab_ajax_view, name='ov_advisor_weekly_slab'),
    url(r'^overview/daily/status$', views.overview.status_ajax_view, name='ov_daily_status'),
    url(r'^overview/daily/wayaway$', views.overview.wayaway_ajax_view, name='ov_daily_wayaway'),
    url(r'^overview/daily/status/slab$', views.overview.status_daily_slab_ajax_view, name='ov_status_daily_slab'),
    url(r'^overview/weekly/status/slab$', views.overview.status_weekly_slab_ajax_view, name='ov_status_weekly_slab'),
    url(r'^overview/appointment/detail$', views.overview.appointment_detail_ajax_view, name='ov_appointment_detail'),
    url(r'^overview/update/creaditcard$', views.overview.appointment_update_creditcard, name='ov_update_cc'),
    url(r'^overview/update/updateodoout$', views.overview.appointment_update_odoout, name='ov_update_odoout'),
    url(r'^overview/update/vehicle$', views.overview.appointment_update_vehicle, name='ov_update_vehicle'),
    url(r'^overview/update/insurance$', views.overview.appointment_update_insurance, name='ov_update_insurance'),
    #appointment
    url(r'^appointment/$', views.appointment.appointment, name='appointment'),
    url(r'^appointment/create/update', views.appointment.appointment_create_update, name='appointment_create_update'),
    url(r'^appointment/customer$', views.appointment.appointment_customer_ajax_view, name='appointment_customer'),
    url(r'^appointment/customer/vehicle/delete$', views.appointment.customer_delete_vehicle_ajax_view, name='appointment_customer_vehicle_delete'),
    url(r'^appointment/update/time$', views.appointment.appointment_time_ajax_view, name='appointment_update_time'),
    url(r'^appointment/wayaway$', views.appointment.appointment_wayaway_ajax_view, name='appointment_wayaway'),
    url(r'^appointment/wayaway/save$', views.appointment.appointment_wayaway_save_ajax, name='appointment_wayaway_save'),
    url(r'^appointment/repair$', views.appointment.appointment_repair_ajax_view, name='appointment_repair'),
    url(r'^appointment/accountinfo$', views.appointment.appointment_account_info_ajax_view, name='appointment_accountinfo'),
    url(r'^appointment/book', views.appointment.appointment_book_ajax_view, name='appointment_book'),
    url(r'^appointment/remove/service', views.appointment.appointment_remove_service, name='appointment_remove_service'),

    #customers
    url(r'^customers/$', views.customers.customers, name='customers'),
    url(r'^customers/add/user$', views.customers.save_customer_ajax, name='customers_add_user'),
    url(r'^customers/add/vehicle$', views.customers.save_vehicle_ajax, name='customers_add_vehicle'),
    url(r'^customers/add/appointment$', views.customers.save_appointment_ajax, name='customers_add_appointment'),
    url(r'^customers/add/reminder', views.customers.save_guest_reminder_ajax, name='customers_add_reminder'),
    #repair and servicea
    url(r'^rservices/$', views.rservices.rservices, name='rservices'),
    url(r'^rservices/form$', views.rservices.get_rservices_form, name='rservices_form'),
    url(r'^rservices/create/update', views.rservices.rservices_create_update, name='rservices_create_update'),
    url(r'^rservices/delete', views.rservices.rservices_delete, name='rservices_delete'),
    #dealership_manage
    url(r'^manage/$', views.manage.manage, name='manage'),
    url(r'^manage/deatil$', views.manage.details, name='manage_details'),
    url(r'^manage/user_term_advisor$', views.manage.add_user_advisor, name='add_user_advisor'),
    url(r'^manage/add_amenities$', views.manage.add_amenities, name='add_amenities'),
    url(r'^manage/delete_amenities$', views.manage.delete_amenities, name='delete_amenities'),
    url(r'^manage/get_resource_link$', views.manage.get_resource_link, name='get_resource_link'),
    url(r'^manage/add_resource_link$', views.manage.add_resource_link, name='add_resource_link'),
    url(r'^manage/delete_resource_link$', views.manage.delete_resource_link, name='delete_resource_link'),
    url(r'^manage/update_resource_link$', views.manage.update_resource_link, name='update_resource_link'),
    url(r'^manage/get_shopcontacts$', views.manage.get_shopcontacts, name='get_shopcontacts'),
    url(r'^manage/add_shopcontacts$', views.manage.add_shopcontacts, name='add_shopcontacts'),
    url(r'^manage/delete_shopcontacts$', views.manage.delete_shopcontacts, name='delete_shopcontacts'),
    url(r'^manage/update_shopcontacts$', views.manage.update_shopcontacts, name='update_shopcontacts'),
    url(r'^manage/get_marketing$', views.manage.get_marketing, name='get_marketing'),
    url(r'^manage/add_marketing$', views.manage.add_marketing, name='add_marketing'),
    url(r'^manage/get_feedback$', views.manage.get_feedback, name='get_feedback'),
    url(r'^manage/add_feedback$', views.manage.add_feedback, name='add_feedback'),
    url(r'^manage/get_serviceemail$', views.manage.get_serviceemail, name='get_serviceemail'),
    url(r'^manage/add_serviceemail$', views.manage.add_serviceemail, name='add_serviceemail'),
    url(r'^manage/delete_email$', views.manage.delete_email, name='delete_email'),
    url(r'^manage/update_email$', views.manage.update_email, name='update_email'),
    url(r'^manage/get_sms$', views.manage.get_sms, name='get_sms'),
    url(r'^manage/add_sms$', views.manage.add_sms, name='add_sms'),
    url(r'^manage/delete_sms$', views.manage.delete_sms, name='delete_sms'),
    url(r'^manage/update_sms$', views.manage.update_sms, name='update_sms'),
    url(r'^manage/get_shphr$', views.manage.get_shophrs, name='get_shophrs'),
    url(r'^manage/add_shphr$', views.manage.add_shophrs, name='add_shophrs'),
    url(r'^manage/delete_shphr$', views.manage.delete_shophrs, name='delete_shophrs'),
    url(r'^manage/update_shphr$', views.manage.update_shophrs, name='update_shophrs'),
    url(r'^manage/get_holidays$', views.manage.get_holidays, name='get_holidays'),
    url(r'^manage/add_holiday$', views.manage.add_holiday, name='add_holiday'),
    url(r'^manage/delete_holiday$', views.manage.delete_holiday, name='delete_holiday'),
    url(r'^manage/update_holiday$', views.manage.update_holiday, name='update_holiday'),
    url(r'^manage/get_uaform$', views.manage.get_user_advisor_form, name='get_uaform'),

src/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'BMW.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^dealership/', include('dealership.urls', namespace="dealership")),
    url(r'^dealership/', include('dealership.urls', namespace='dealership' , app_name='dealership')),
    url(r'^livechat/', include('livechat.urls', namespace='livechat')),
    url(r'^customer/', include('customer.urls', namespace='customer')),
    url(r'^flagger/', include('flagging.urls', namespace='flagging')),
    url(r'^mobilecheckin/', include('mobilecheckin.urls', namespace='mobilecheckin' , app_name='mobilecheckin')),
    url(r'^admin/', include(admin.site.urls)),
#     url(r'^subview', include('subview.urls')),

# url(r'^oauth2/', include('oauth2_authentication.urls', namespace="oauth2"))

)
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

src/dealership/views/chat.py
from django import forms
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect

from dealership import conf
from dealership.decorators import dealer_group_check
from dealership.forms import *
from dealership.services.userservices import UserService
from livechat.forms import UploadForm
from livechat.services.channels import ChannelService


# @user_passes_test(dealer_group_check,login_url=conf.REDIRECT_URL)
def chats(request):
    service = ChannelService()
    template_name = 'dealership/chats/index.html'
    channels = service.get_all_channels(request.user.id)

    img=UploadForm()

    context = {"CENTRIFUGE_URL":settings.CENTRIFUGE_URL,
                                          "CENTRIFUGE_SECRET":settings.CENTRIFUGE_SECRET,
                                        "advisor":request.user,

                                             "channels":channels,
#                                            "advisor":user,
                                         'imgform':img,}
    return render(request, template_name,context)


# @user_passes_test(dealer_group_check,login_url=conf.REDIRECT_URL)
def chat(request):
    service = ChannelService()
    template_name = 'dealership/chats/singlechat.html'
    channel = None
    img=UploadForm()

    if request.GET.get("chat_id"):
        channel =service.get_chat(request.GET.get("chat_id"))
    elif request.GET.get("channel") and request.GET.get("advisor") and request.GET.get("guest_user") :
        channel = service.getchannel(request.GET["channel"],request.GET["guest_user"],request.GET["advisor"])

    context = {"CENTRIFUGE_URL":settings.CENTRIFUGE_URL,
                                          "CENTRIFUGE_SECRET":settings.CENTRIFUGE_SECRET,
                                        "advisor":request.user,
#                                              "advisor":user,

                                         'form':img,"channel":channel}
    return render(request, template_name,context)

src/dealership/views/notifications.py
from dealership.models import Notifications
from dealership.factories import DealerShipServicesFactory
from django.http import JsonResponse
from flagging import Constants
from django.utils import timezone


def getRoleOfUser(user):
    role = user.groups.all()
    roleString = ""
    for r in role:
        roleString += r.name + ","
    return roleString


def reset_live_notifications(request):
    # Quick and dirty to send messages to client.
    # Probably should be rolled in to existing messaging system Centrifuge and

    if not request.user.is_authenticated():
        return JsonResponse({'result': "Error"})

    role = getRoleOfUser(request.user)
    if role == "":
        return JsonResponse({'result': "Error"})

    userprofile = request.user.userprofile
    userprofile.last_live_notification = timezone.now()
    userprofile.save()
    return JsonResponse({'result': "OK"})


def get_live_notifications(request):
    if not request.user.is_authenticated():
        return JsonResponse({'result': "Error"})

    dealer_factory = DealerShipServicesFactory()
    notificationservice = dealer_factory.get_instance("notification")

    user = request.user

    userprofile = request.user.userprofile
    lastmessage_timestamp = userprofile.last_live_notification
    if lastmessage_timestamp == None:
        userprofile.last_live_notification = timezone.now()

    role = getRoleOfUser(user)
    if role == "":
        return JsonResponse({'result': "Error"})

    notifications = Notifications.objects.filter(dealer__id=user.userprofile.dealer_id,
                                                 timestamp__gt=lastmessage_timestamp).order_by("timestamp")
    if notifications.count() == 0:
        # Indication time of last message
        userprofile.last_live_notification = timezone.now()
        userprofile.save()
        return JsonResponse({'result': "OK", 'messages': []})

    messages = []
    approved_recipient = False

    for notification in notifications:

        if user != notification.sender:
            # Only send messages if user logged in getting message is not the sender.
            if Constants.TECHNICIAN in role:
                if Notifications.DESTINATION_TECHNICIAN in notification.recipient_groups:
                    approved_recipient = True
            if Constants.ADVISOR in role:
                if Notifications.DESTINATION_ADVISOR in notification.recipient_groups:
                    approved_recipient = True
            if Constants.DEALER in role:
                if Notifications.DESTINATION_DEALER in notification.recipient_groups:
                    approved_recipient = True
            if Constants.PARTS in role:
                if Notifications.DESTINATION_PARTS in notification.recipient_groups:
                    approved_recipient = True

            if notification.recipient_users:
                for destination_user in notification.recipient_users.all():
                    if user == destination_user:
                        approved_recipient = True

            if approved_recipient:
                messages.append(
                    {"message": notification.message, 'timestamp': notification.timestamp, 'id': notification.id})

        lastmessage_timestamp = notification.timestamp

    # Indication time of last message
    userprofile.last_live_notification = lastmessage_timestamp
    userprofile.save()

    return JsonResponse({'result': "OK", 'messages': messages})

src/dealership/templates/overview/carryover_time.html
<div id="time-carryover-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
	<div class="modal-dialog">
    	<div class="modal-content">
        	<div class="modal-content">
          		<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				    <h4 class="modal-title">Carryover Appointment</h4>
				</div>
				<div class="modal-body">
					<div>
						<form id="form-carryover-time" class="save-form pending">
							<input id="appointment_id" name="id" type="hidden"/>
							<div>
<div class="row mb-10 clearfix">
<div class="col-sm-4 text-right">Appointment Date/Time:</div>
<div class="col-sm-8  text-left">&nbsp; <span id="appt_actual_time"></span></div>
</div>
<div class="row mb-10 clearfix">
<div class="col-sm-4 text-right">Appointment Duration:</div>
<div class="col-sm-8  text-left">&nbsp;</div>
</div>
<div class="row mb-10 clearfix">
<div class="col-sm-4 text-right">Carryover Date:</div>
<div class="col-sm-8  text-left">&nbsp; 
<div class="DatePickerBtn">
<a class="carryover-date-control pointer" id="carryover-date-prev">
<span aria-hidden="true" class="glyphicon glyphicon-chevron-left"></span>
</a>
<input name="start_time" id="carryover-date-text" class="ml-10 mr-10"/> 
<a class="carryover-date-control pointer" id="carryover-date-next">
<span aria-hidden="true" class="glyphicon glyphicon-chevron-right"></span>
</a>
<a class="pointer ml-10 carryover-date-picker">
<span aria-hidden="true" class="glyphicon glyphicon-calendar"></span>
</a>
</div>
</div>
</div>
<div class="row mb-10 clearfix">
<div class="col-sm-4 text-right">Carryover Duration:</div>
<div class="col-sm-8  text-left">&nbsp; <a href="#">{{ customer.email_1 }}</a></div>
</div>
<div class="row mb-10 clearfix">
<div class="col-sm-4 text-right">Notes:</div>
<div class="col-sm-8  text-left"> <textarea></textarea></div>
</div>
						    </div>
						    <button type="submit" id="form-carryover-time-submit" class="submit btn btn-default">submit</button>
						</form>
					</div>
				</div>
    		</div>
    	</div>
  	</div>
</div>


<div id="time-carryover-confirmation-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
	<div class="modal-dialog">
    	<div class="modal-content">
        	<div class="modal-content">
          		<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				    <h4 class="modal-title">Carryover Appointment</h4>
				</div>
				<div class="modal-body">
					Appointment time has been updated
				</div>
			</div>
		</div>
	</div>
</div>





   

src/dealership/templates/overview/filters.html
<div class="row">
        	<div class="col-sm-3">
            	<h4>Today's Appointments</h4>
            </div>
            <div class="col-sm-6">
            	<div rel="time" class="btn-group main_filter">
                	<a rel="time" class="btn btn-info">Time</a>
                    <a rel="advisor" class="btn btn-default">Advisor</a>
                    <a rel="status" class="btn btn-default">Status</a>
                </div>
            </div>
            <div class="col-sm-3">
            	<a id="new-appointment-btn" class="btn btn-default">New Appointment</a>
                <button type="button" class="newcustomer_button btn btn-default">New Customer</button>
            </div>
        </div>
        <div class="clear pad-10"></div>
        <div class="row">
        	<div class="col-sm-3"></div>
            <div rel="daily" class="col-sm-3 sub_filter">
            	<a rel="daily" class="btn btn-info">Day View</a>
                <a rel="weekly" class="btn btn-default">Week View</a>
            </div>
            <div class="col-sm-3 text_13">
            	<div class="DatePickerBtn btn-default">
            	<a class="filter-date-control pointer" id="filter-date-prev"><span aria-hidden="true" class="glyphicon glyphicon-chevron-left"></span></a>
                <a id="filter-date-text" class="ml-10 mr-10"></a>
             
                <a class="filter-date-control pointer" id="filter-date-next"><span aria-hidden="true" class="glyphicon glyphicon-chevron-right"></span></a>
                <a class="pointer ml-10 filter-date-picker"><span aria-hidden="true" class="glyphicon glyphicon-calendar"></span></a>
            </div>
            </div>
            
            	<!--
            	<div class="input-group date">
				  <input type="text" class="form-control"><span class="input-group-addon"><i class="fa fa-calendar"></i></span>
				</div>
				-->
				
            <div class="col-sm-3">
            	<div class="btn-group">
                    <button type="button" class="appts-print btn btn-default"><span class="glyphicon glyphicon-print mr-10"></span> Print</button>
                    {% comment %}
  					<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span aria-hidden="true" class="glyphicon glyphicon-print mr-10"></span>Print</button>
  					<ul id="appts-print" class="dropdown-menu">
                        <li><a href="#" class="appts-print" data-url="appts-print-all">Print All Today`s Appts</a></li>
                        <li><a href="#" class="appts-print" data-url="appts-print-open">Print Open Appts. Only</a></li>
                    </ul>
                    {% endcomment %}
				</div>
            </div>
        </div>
        
        <div class="clear pad-20"></div>
  		<script>
  		$(function(){
  			$(".appts-print").off("click").on("click",function(){
  			    // var d = $(this).data('url');
  				print($("#main_content"));
  			});
  		});
  		</script>

src/dealership/templates/overview/loader.html
{% load staticfiles %}
<div class"slabs_loader">
	<img src="{% static "images/loader.png" %}"/>
</div>

src/dealership/templates/overview/searchcustomer.html
<div>search customer</div>

<form id="searchcust_form" action="{% url 'dealership:searchcustomer' %}" method="post">
	{% csrf_token %}
    <div class="form-group">
    	{% for choice in searchform.options %}
    		<div  class="radio">
	            <label>{{ choice.tag }} <span>{{ choice.choice_label }}</span></label>
	        </div>
		{% endfor %}
    </div>
    <div class="form-group">
    	{{ searchform.criteria }}
    </div>
    <button  type="submit" class="btn btn-info" id="submit">Ok</button>
</form> 

src/dealership/templates/overview/time_daily.html
{% block breadcrumbs %}
	{% include "dealership/app/breadcrumb.html" %}  
{% endblock %}

<span class="open-time hidden">{{timings.open_time_string}}</span>
<span class="close-time hidden">{{timings.close_time_string}}</span>
<span class="slot-duration hidden">{{timings.slot}}</span>
	
<div id="ajax_main_content">	
	<div id="overview_time_daily" class="OverviewTimeDailyGrid">
		<table class="table table-striped mb-0">
	    	<thead>
	        	<tr>
	              <th class="col-lg-1">TIME</th>
	              <th class="col-lg-2">CUSTOMER NAME</th>
	              <th class="col-lg-2">VEHICLE/COLOR/LP#</th>
	              <th class="col-lg-1">VIN#</th>
	              <th>SERVICE SCHEDULED</th>
	              <th class="col-lg-1">A WAY AWAY</th>
	              <th class="col-lg-2">ADVISOR</th>
	              <th class="col-lg-1">STATUS</th>
	            </tr>
	        </thead>        
	    </table>
	</div>
</div>

src/dealership/templates/overview/time_daily_multi_slab.html
{% for slab in slabs %}
	<div id="time_daily_slab_{{ slab.id }}" class="GridRow daily_view_table" > <tbody id=>
		{% include "overview/time_daily_slab.html" %} 
	</div>
{% endfor %}

src/dealership/templates/overview/time_daily_row.html
<tr class="appointment_row" rel="{{ row.id }}" id="appointment_{{ row.id }}">
  <td class="col-lg-1">
  	<a href="#" class="dropdown-toggle text_grey" data-toggle="dropdown" role="button" aria-haspopup="true" 
    aria-expanded="false">{{ row.time }}</a>
    <ul class="dropdown-menu">
        <li><a datetime="{{ row.datetime }}" rel="{{ row.id }}" class="time-carryover pointer">Carry Over</a></li>
        <li><a datetime="{{ row.datetime }}" rel="{{ row.id }}" class="time-adjust pointer">Adjust Time</a></li>
        <li><a class="time-manage-override pointer">Manage Override</a></li>
    </ul> 
  	
  </td>
  <td class="col-lg-2"><a class="customer pointer"  vehicle_id="{{ row.vehicle.id }}" customer_id="{{ row.customer.id }}" rel="{{ row.id }}">{{ row.customer.name }}</a></td>
  <td class="col-lg-2">{{ row.vehicle.detail }}</td>
  <td class="col-lg-1">
  	<a href="#" class="dropdown-toggle text_grey" data-toggle="dropdown" role="button" aria-haspopup="true" 
    aria-expanded="false">{{ row.vehicle.vin }}</a>
    <ul class="dropdown-menu">
        <li><a href="#">RO History</a></li>
    </ul>  	
  </td>
  
  
  <td class="dropdown dropdown-hover col-lg-2">
    <a href="#" class="dropdown-toggle text_grey" data-toggle="dropdown" role="button" aria-haspopup="true" 
    aria-expanded="false">
    {% if row.service.combined_name%}
    	{{ row.service.combined_name }}
    {% else %}
    	Select Services
    {% endif %}
    </a>
    <ul class="dropdown-menu">
        <li><a href="{% url 'dealership:appointment' %}?panel=service&customer_id={{ row.customer.id }}&appointment_id={{ row.id }}&vehicle_id={{ row.vehicle.id }}">Change Service/Repair</a></li>
    </ul>
  </td>
  <td class="dropdown dropdown-hover col-lg-1">
    <a href="#" class="dropdown-toggle text_grey dd_wayaway_title" data-toggle="dropdown" role="button" aria-haspopup="true" 
    aria-expanded="false">
    {% if row.wayaway %}
    	{{ row.wayaway }}
    {% else %}
    	Select Wayaway
    {% endif %}
    </a>
    <ul rel="way_away_id" class="dropdown-menu dropdown-change-apt">
    </ul>
  </td>
  <td class="dropdown dropdown-hover col-lg-2">
  	<a href="#" class="dropdown-toggle text_grey dd_advisor_title" time="{{ row.datetime }}" data-toggle="dropdown" role="button" aria-haspopup="true" 
    aria-expanded="false">
	  	{% if row.advisor %}
	    	{{ row.advisor }}
	    {% else %}
	    	Select Advisor
	    {% endif %}  
	 </a>
	 <ul rel="advisor_id" class="dropdown-menu dropdown-change-apt">
    </ul>
  	</td>
  <td class="dropdown dropdown-hover col-lg-1">    
    <a href="#" class="dropdown-toggle text_grn dd_status_title" data-toggle="dropdown" role="button" aria-haspopup="true" 
    aria-expanded="false">{{ row.status }}</a>
    <ul rel="appointment_status_id" class="dropdown-menu dropdown-change-apt dropdown-menu-status pull-right">
    </ul>
  </td>
</tr>



<tr class="hidden" id="appointment_detail_{{ row.id }}">
	
</tr>
	

src/dealership/templates/overview/time_weekly_row.html
<tr id="appointment_{{ row.id }}">
  <td>{{ row.time }}</td>
  <td>{{ row.customer.name }}</td>
  <td>
  	<span data-toggle="tooltip" title="Model detail`ll be here">{{ row.vehicle.model }}</span> / 
    <span data-toggle="tooltip" title="Make detail`ll be here">{{ row.vehicle.make }}</span> / 
    <span data-toggle="tooltip" title="Year detail`ll be here">{{ row.vehicle.year }}</span>
  </td>
</tr>