src/customer/urls.py
from django.conf.urls import url

from customer.views import login, main, vehicle, account, notifications, appoint, service , statusalert,cart


urlpatterns = [
    url(r'^$', login.login, name='index'),
#     url(r'^import_csv$', login.import_csv, name='index'),
    url(r'pull_models', login.pull_models, name='pull_models'),
    url(r'create_models', login.create_models, name='create_models'),
    url(r'delete_models', login.delete_models, name='delete_models'),
    url(r'create_models', login.create_models, name='create_models'),
    url(r'^login/(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', login.login, name='login'),
    url(r'^login/?$', login.login, name='login'),
    url(r'^password/reset/$', login.passreset, name='passreset'),
    url(r'^username/reset/$', login.userreset, name='userreset'),
    url(r'^password/create$', login.passcreate, name='passcreate'),
    url(r'^main/$', vehicle.mainview , name='main'),
    url(r'^accountsettings/$', account.accountview , name='accountsettings'),
    url(r'^logout/$', login.logout, name='logout'),
    url(r'^test_ocr/$', main.test_ocr, name='test_ocr'),
    url(r'^puller/$', main.test_puller, name='puller'),
    url(r'^vehiclewidget/$', vehicle.get_vehicle, name='vehiclewidget'),
    url(r'^delete_vehicle/$', vehicle.del_vehicle, name='del_vehicle'),
    url(r'^ocr_snap/$', vehicle.ocr_snap, name='ocr_snap'),
    url(r'^delete_account/$', account.delete, name='delete_account'),
    url(r'^notifications/$', notifications.notificationssettings, name='notifications'),
    url(r'^findapp/$', appoint.find_exiting_appointment, name='findapp'),
    url(r'^search_app/$', appoint.search_app, name='search_app'),#used for searching thourhg ajax
    url(r'^new_customer_vehicle/$', login.new_customer_vehicle, name='new_customer_vehicle'),
    url(r'^vehicle_selection_appointment/$', appoint.vehicle_selection, name='vehicle_selection_appointment'),
    url(r'^service_selection_appointment/$', appoint.service_selection_appointment, name='service_selection_appointment'),
    url(r'^date_selection_appointment/$', appoint.date_selection_appointment, name='date_selection_appointment'),
    url(r'^get_all_services_ajax/$', service.get_all_services, name='get_all_services_ajax'),
    url(r'^save_appointment_services_ajax/$', service.save_all_services, name='save_appointment_services_ajax'),
    url(r'^get_all_advisors_ajax/$', service.get_all_advisor, name='get_all_advisors_ajax'),
    url(r'^save_advisor_ajax/$', service.save_advisor, name='save_advisor_ajax'),
    url(r'^schedule_appointment/$', appoint.schedule_appointment, name='schedule_appointment'),
    url(r'^cancel_appointment/$', appoint.cancel_appointment, name='cancel_appointment'),
     url(r'^search_by_code_phone/$', appoint.search_by_code_phone, name='search_by_code_phone'),
     url(r'^book_appointment/$', appoint.book_appointment, name='book_appointment'),
     url(r'^check_username_exist/$', login.check_username, name='check_username'),
    url(r'^createuser/$', login.createuser, name='createuser'),
     url(r'^registeruser/$', login.registeruser, name='registeruser'),
    url(r'^sendemail/$', appoint.sendemail, name='sendemail'),
    url(r'^testingurl/$', login.testing, name='testingurl'),
     url(r'^uploadvin/$', appoint.uploadvin, name='uploadvin'),
     url(r'^book_appointment_now_new/$', appoint.book_appointment_now_new, name='book_appointment_now_new'),
     url(r'^book_appointment_now_existing/$', appoint.book_appointment_now_existing, name='book_appointment_now_ext'),
      url(r'^get_available_slabs_for_date/$', appoint.get_available_slabs_for_date, name='get_available_slabs_for_date'),
      url(r'^check_userprofile/$', appoint.check_userprofile, name='check_userprofile'),
      url(r'^get_available_adivsors_for_date/$', appoint.get_available_adivsors_for_date, name='get_available_adivsors_for_date'),
      url(r'^save_appointment_now_ext/$', appoint.save_appointment_now_ext, name='save_appointment_now_ext'),
      # url(r'^statusalert/(?P<appointment_id>\d+)/$', statusalert.index, name='status_alert_index'),
      url(r'^statusalert/(?P<appointment_hash>[0-9A-F]{56})/$', statusalert.index_hash, name='status_alert_index_hash'),

    url(r'^approvestatus/(?P<appointment_id>\d+)/$', statusalert.approve_recommendations, name='approve_status'),

       url(r'^replystatus/(?P<appointment_id>\d+)/$', statusalert.reply, name='reply_status'),

        url(r'^getcart/$', cart.get_cart, name='getcart'),
    url(r'^send_activation_code/$', service.send_activation_code, name='send_activation_code'),
     url(r'^save_customer_number/$', service.save_customer_number, name='save_customer_number'),

       url(r'^paymentstatus/(?P<appointment_id>\d+)/$', statusalert.payment, name='payment_status'),
       url(r'^getcart/$', cart.get_cart, name='getcart'),
        url(r'^download_calendar/$', appoint.download_calendar, name='download_calendar'),
        url(r'^sync_gcalendar/$', login.sync_gcalendar, name='sync_gcalendar'),

        url(r'oauth2callback', login.auth_return, name='return'),
        url(r'print_appointment', appoint.print_appointment, name='print_appointment'),
        url(r'^service_history/(?P<vehicle_id>[a-zA-Z0-9_-]+)/?$', vehicle.service_history, name='service_history'),
         url(r'^(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', login.index, name='index'),



]

src/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'BMW.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^dealership/', include('dealership.urls', namespace="dealership")),
    url(r'^dealership/', include('dealership.urls', namespace='dealership' , app_name='dealership')),
    url(r'^livechat/', include('livechat.urls', namespace='livechat')),
    url(r'^customer/', include('customer.urls', namespace='customer')),
    url(r'^flagger/', include('flagging.urls', namespace='flagging')),
    url(r'^mobilecheckin/', include('mobilecheckin.urls', namespace='mobilecheckin' , app_name='mobilecheckin')),
    url(r'^admin/', include(admin.site.urls)),
#     url(r'^subview', include('subview.urls')),

# url(r'^oauth2/', include('oauth2_authentication.urls', namespace="oauth2"))

)
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

src/customer/models.py
from django.contrib.auth.models import User
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.db import models
from oauth2client.contrib.django_orm import FlowField, CredentialsField

from dealership.models import Questions, Appointment


class FlowModel(models.Model):
    id = models.OneToOneField(Appointment, primary_key=True)
    flow = FlowField()


class CredentialsModel(models.Model):
    id = models.OneToOneField(Appointment, primary_key=True)
    credential = CredentialsField()

src/customer/views/account.py
import os

from PIL import Image
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.core import serializers
from django.core.urlresolvers import reverse
from django.http.response import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
import pytesseract

from customer.app_confg import confg
from customer.decorators.decorators import customer_group_check
from customer.forms import CustomerVehicleForm, CustomerAccountForm, \
    CustomerInsuranceForm, CreditDebitForm

from dealership.forms import ChangePasswordForm

from customer.factories import CustomerServicesFactory
import json as mainjson
from livechat.forms import UploadForm


@user_passes_test(customer_group_check,login_url=confg.REDIRECT_URL)
def delete(request):
        try:
            customer_factory = CustomerServicesFactory()
            user = request.user
            service = customer_factory.get_instance("account")#AccountService()
            resp = service.delete_account(user.userprofile)
            if resp:
                messages.success(request, "Account Deleted Successfully")
            else:
                messages.success(request, "Unable to Delete Account")
        except:
            messages.error(request, "Unable to  Deleted account. Try later")
        return HttpResponseRedirect(reverse("customer:accountsettings"))


@user_passes_test(customer_group_check,login_url=confg.REDIRECT_URL)
def accountview(request):
    """
            This is the account view where oyu can sae the account information
    """
    customer_factory = CustomerServicesFactory()
    user = request.user
    dealer_code = request.session["dealer_code"]
    account_service =  customer_factory.get_instance("account")
    service = customer_factory.get_instance("user")
    template_name = 'customer/customer_account.html'
    name = request.user.first_name+" "+request.user.last_name
    userprofile =service.get_userprofile(request.user)
    insurance_profile = service.get_user_driver_insurance(userprofile)
    cc_profile = service.get_cc_profile(userprofile)
    account_initial = account_service.get_initial_user_form(user, userprofile)
    driver_initial  =account_service.get_initial_driver_form(user, insurance_profile,userprofile)
    cc_initial = account_service.get_initial_cc_form(user,cc_profile,userprofile)
    customer_form =CustomerAccountForm(instance=userprofile,initial=account_initial)
    driver_form = CustomerInsuranceForm(instance=insurance_profile,initial=driver_initial)
    cc_form = CreditDebitForm(instance=cc_profile,initial=cc_initial)
    pass_form = ChangePasswordForm()
    tab = "account"

    if request.method == 'POST':
        resp = False
        password_changed=False

        if request.POST.get("type") == "account":

            customer_form = CustomerAccountForm(request.POST,instance=userprofile)
            resp = account_service.save_account_form(user,userprofile,customer_form,account_initial)
            msg = "Account Information saved  successfully" #

        elif request.POST.get("type")=="driver":
            driver_form = CustomerInsuranceForm(request.POST,instance = insurance_profile)
            resp = account_service.save_driver_form(insurance_profile,driver_form)
            msg = "Driver License and Insurance Information saved  successfully"

        elif request.POST.get("type")=="cc":
            cc_form = CreditDebitForm(request.POST,instance = cc_profile)
            resp = account_service.save_cc_form(cc_profile,cc_form)
            msg =  "Debit/Credit form save successfully"

        elif request.POST.get("type")=="change_password":
            pass_form = ChangePasswordForm(request.POST)
            resp = account_service.save_password_form(pass_form,user)
            msg =  "Password Changed successfully"
            password_changed = True
        if password_changed:
            messages.success(request, msg)
            return  HttpResponseRedirect(reverse("customer:index")+"?dealer_code="+dealer_code)
        elif resp:
            messages.success(request, msg)
            return  HttpResponseRedirect(reverse("customer:accountsettings"))


    else:
        customer_form = CustomerAccountForm(instance=userprofile,initial=account_initial)
        driver_form = CustomerInsuranceForm(instance=insurance_profile,initial=driver_initial)
        cc_form = CreditDebitForm(instance=cc_profile,initial=cc_initial)
        pass_form = ChangePasswordForm()


    context = {"page_title":"Customer Profile","tab":tab,
                                          "customer_form":customer_form,
                                          "driver_form":driver_form,
                                          "cc_form":cc_form,
                                          "pass_form":pass_form,
                                         "dealer_code":dealer_code,
                                          'active' : True,
                                          }
    service.set_centrifuge_context(request,dealer_code,userprofile, context,chatposition="top")
    return render(request, template_name,context)





#     return CustomerAccountForm(initial=initial,instance=userprofile)

src/customer/views/cart.py
import datetime

from PIL import Image
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect, Http404, JsonResponse
from django.shortcuts import render
from django.utils import timezone

from django.conf import settings
from customer.app_confg import confg
from customer.decorators.decorators import dealership_required, dealership_required_or_logged_in, \
    appointment_required, customer_group_check
from customer.factories import CustomerServicesFactory
from customer.forms import CustomerVehicleForm, CustomerAccountForm, \
    GuestccountForm, UploadVinForm
from dealership.factories import DealerShipServicesFactory
from dealership.forms import LoginForm, CreateUserForm
from dealership.models import CustomerVehicle, UserProfile, Appointment
import json as mainjson


@appointment_required
@dealership_required_or_logged_in
def get_cart(request,dealer_code,profile,appointment):
    try:
        if appointment:

                customer_factory = CustomerServicesFactory()
                dealer_factory = DealerShipServicesFactory()
                dealer_service = dealer_factory.get_instance("dealership")
                dealer = dealer_service.get_dealer_by(dealer_code)
                userservice = customer_factory.get_instance("user")
                appointmentservice = dealer_factory.get_instance("appointment")
                repairservice = dealer_factory.get_instance("repair")
                services = repairservice.get_service_for(appointment.id,'s')
                repairs = repairservice.get_service_for(appointment.id,'r')
                print services
                print repairs

                context = {
                                        "mainurl":settings.MEDIA_ROOT,
                                          "appointment":appointment,
                                          "dealer_code":dealer_code,
                                          "services":services,"repairs":repairs,
                                          "cart_count":len(repairs)+len(services)

                }

                return render(request, "customer/cart/main.html",context)
        else:
#             return ""
            return render(request, "customer/cart/main.html",{})
    except Exception,e:
        print e

src/customer/views/paypal_execute.py
import paypalrestsdk
import logging
logging.basicConfig(level=logging.INFO)

# ID of the payment. This ID is provided when creating payment.
payment = paypalrestsdk.Payment.find("PAY-28103131SP722473WKFD7VGQ")

# PayerID is required to approve the payment.
if payment.execute({"payer_id": "DUFRQ8GWYMJXC"}):  # return True or False
    print("Payment[%s] execute successfully" % (payment.id))
else:
    print(payment.error)

src/customer/templates/customer/layouts/appointment_base.html
{% extends "customer/layouts/second_base.html" %}
{% load staticfiles %}

{%block main%}
	 <div class="clearfix">
			
						<!-- {%include "customer/appointment/partials/appointment_tabs.html"%} -->
						{% block submain %}
						
						{% endblock%}
	</div>
		
{%endblock%}

{% block js %}
	{{block.super}}
	<script src="{% static "js/dealership.js" %}"></script>
	<script src="{% static "js/dealership_overview.js" %}"></script>
	<script src="{% static "js/dealership_appointment.js" %}"></script>
	<script src="{% static "customer/js/cart.js" %}"></script>
	<script src="{% static "customer/js/bootstrap-tabcollapse.js" %}"></script>
	<script>
		$(document).ready(function(){
			{% if appointment %}
				window.cart= new Cart();
				window.cart.url = "{% url 'customer:getcart' %}"
				window.cart.cart_container = $("#cart_main");
				window.cart.appointment_id = {{appointment.id}}
				window.cart.dealer_code = "{{dealer_code}}"
				window.cart.fillCart()
			{%endif%}
		});
		
	</script>
{% endblock%}


</body>
</html>

src/customer/templates/customer/layouts/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		{% block html_header %}
			{% include 'customer/includes/htmlheader.html' %}
		{%endblock%}
	</head>
	<body class="bg LoginBg" style="background-image:url(
      {% if dealership.customer_portal_header_image %}
      {{dealership.customer_portal_header_image.url}}
      {% else %}
      {% static "customer/images/default_store_header.png" %}
      {% endif %});"
	
			{%block header%}
				{%include 'customer/includes/header.html'%}
			{%endblock%}
			<div class="container">
				<div class="row relative">
					{%block messages%}
						{%include 'customer/includes/messages.html' %}
					{%endblock%}
				</div>
			</div>
			<div class="container-fluid">

				<div class="row">
						<div class="pad-20"></div>
				    	<div class="col-sm-6">
				            <h3 class="mt-0">{{page_title}}</h3>
				        </div>
			        	<div class="col-sm-6 mt-15">
			        	
			        		
								    	<div class="dropdown pull-right " id="cart_main">
								        
								        </div>
								        <div class="pull-right login-container">
								        	 {% if user.is_authenticated and user.groups.all.0|lower == "customer" %}
							           				 Welcome {{user.userprofile.first_name}} {{user.userprofile.last_name}} &nbsp;
							            			 <a href="{%url 'customer:main'%}"> (My Details/ Account)</a>  &nbsp;
							            			 <a href="{%url 'customer:logout'%}?dealer_code={{dealer_code}}">Log Out</a>  &nbsp;
							            	{%endif%}
						            	</div>
								     
								    	
						</div>
			   
				  
				</div>
	        	{% block main %}
	
				{% endblock%}
			
				
			</div>
			<div id="loading_page">
 				 <img id="loading-image-page" src="{% static "customer/images/ajax-loader.gif" %}" alt="Loading..." />
			</div>
			{% block js %}
			
			<!-- <script src="{% static "js/jquery-1.10.2.min.js" %}"></script> -->
			<!-- <script src="{% static "js/bootstrap.js" %}"></script> -->
			<script src="{% static "customer/js/bootstrap_dialog.js" %}"></script>
			<script src="{% static "customer/js/utility.js" %}"></script>
			<script src="{% static "customer/chosen/chosen.jquery.min.js" %}"></script>
			<script src="{% static "js/moment.min.js" %}"></script>
			<script src="{% static "js/bootstrap-datepicker.min.js" %}"></script>
			{% endblock%}
			{% block extra %}
				 {% if chatadvisor and chatposition == "bottom" %}
					{% include "livechat/chat.html" %}
				{%endif%}
			{%endblock%}
			<div class="modal fade" id="modelimagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel">Image preview</h4>
			      </div>
			      <div class="modal-body">
			        <img src="" id="imagepreviewmodal" style="width: 400px; height: 264px;" >
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			      </div>
			    </div>
			  </div>
</div>
</body>
</html>

src/customer/templates/customer/layouts/index.html
{% extends "customer/layouts/base.html" %}
{% load staticfiles %}

 
 {% block main%}
		 <div class="container">
			<div class="row relative">
		    	<div class="col-sm-offset-1 col-sm-10">
		            <div class="navbar navbar-default yamm CusLoginTabs">
		                <div class="navbar-header">
		                    <button type="button" data-toggle="collapse" data-target="#mobile-nav" class="navbar-toggle">
		                        <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
		                    </button>
		                </div>
		                <div id="mobile-nav" class="navbar-collapse collapse">
		                    {% include 'customer/partials/tabs_login.html'%}
		                </div>
		            </div>
		            <div class="clear"></div>
		            <div class="tabz-data">
		            		      {% block submain%}
		            		      {% endblock %}   
		            </div>
		        </div>
		    </div>
		</div>
		<div class="clear pad-5"></div>
{% endblock %}  


{% block js %}
{{block.super}}
	<!-- <script src="{% static "js/jquery-1.10.2.min.js" %}"></script>
	<script src="{% static "js/bootstrap.js" %}"></script> -->
	<script src="{% static "customer/js/utility.js" %}"></script>
{% endblock%}

src/customer/templates/customer/layouts/loggedin_base.html
{% extends "customer/layouts/second_base.html" %}
{% load staticfiles %}

{%block main%}
	 <div class="clearfix">
			
						{%include "customer/partials/tabs.html"%}
						{% block submain %}
						
						{% endblock%}
	</div>
		
{%endblock%}

{% block js %}
	{{block.super}}
	<script src="{% static "customer/js/utility.js" %}"></script>
{% endblock%}


</body>
</html>

src/customer/templates/customer/layouts/second_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		{% block html_header %}
			{% include 'customer/includes/htmlheader.html' %}
		{%endblock%}
	</head>
	<body class="bg ">
			{%block header%}
				{%include 'customer/includes/header.html'%}
			{%endblock%}
			<div class="container">
				<div class="row relative">
					{%block messages%}
						{%include 'customer/includes/messages.html' %}
					{%endblock%}
				</div>
			</div>
			<div class="container-fluid">

				<div class="row">
						<div class="pad-20"></div>
				    	<div class="col-sm-6">
				            <h3 class="mt-0">{{page_title}}</h3>
				        </div>
			        	<div class="col-sm-6 mt-15">
			        	
			        		
								    	<div class="dropdown pull-right " id="cart_main">
								        
								        </div>
								          <div class="pull-right logout-container">
								        	 <span>{% if user.is_authenticated and user.groups.all.0|lower == "customer" %}
							           				 Welcome {{user.userprofile.first_name}} {{user.userprofile.last_name}} </span>
							            			 <a href="{%url 'customer:main'%}"> (My Details/ Account) </a>
							            			 <a href="{%url 'customer:logout'%}?dealer_code={{dealer_code}}">Log Out</a>  &nbsp;
							           		 {%else%}
							            		
							            		<a href="{%url 'customer:login'%}?dealer_code={{dealer_code}}">Login (My Details/ Account)</a>  &nbsp;
							            	{%endif%}
						            	</div>
								     	
						</div>
						<div class="pad-5"></div>
			   
				  
				</div>
	        	{% block main %}
	
				{% endblock%}
			
				
			</div>
			<div id="loading_page">
 				 <img id="loading-image-page" src="{% static "customer/images/ajax-loader.gif" %}" alt="Loading..." />
			</div>
			{% block js %}
			
			<!-- <script src="{% static "js/jquery-1.10.2.min.js" %}"></script> -->
			<!-- <script src="{% static "js/bootstrap.js" %}"></script> -->
			<script src="{% static "customer/js/bootstrap_dialog.js" %}"></script>
			<script src="{% static "customer/js/utility.js" %}"></script>
			<script src="{% static "customer/chosen/chosen.jquery.min.js" %}"></script>
			<script src="{% static "js/moment.min.js" %}"></script>
			<script src="{% static "js/bootstrap-datepicker.min.js" %}"></script>
			{% endblock%}
			{% block extra %}
				 {% if chatadvisor and chatposition == "bottom" %}
					{% include "livechat/chat.html" %}
				{%endif%}
			{%endblock%}
			<div class="modal fade" id="modelimagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel">Image preview</h4>
			      </div>
			      <div class="modal-body">
			        <img src="" id="imagepreviewmodal" style="width: 400px; height: 264px;" >
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			      </div>
			    </div>
			  </div>
</div>
</body>
</html>

src/customer/templates/customer/layouts/statusalert_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		{% block html_header %}
			{% include 'customer/includes/htmlheader.html' %}
		{%endblock%}
	</head>
	<body>
	<header>
	<div class="page-header">
        <div class="container-fluid">
        	<div class="row">
            	<div class="col-sm-6">
		                <a href="index.html" class="logo">
		                {% if dealership.customer_portal_header_image %}
		                <img src="{{dealership.customer_portal_header_image.url}}" width="60" />
		                {% else %}
		                <img src="{% static 'customer/images/logo.png' %}" width="60" />
		                {% endif %}
		                </a>
                    <h1>BMWSF Service Scheduler</h1>
                </div>
                
            </div>
        </div>
    </div>
</header>
<div class="clear"></div>
{% block main %}
{% endblock %}
<div id="loading_page">
	<img id="loading-image-page" src="{% static "customer/images/ajax-loader.gif" %}" alt="Loading..." />
</div>
</body>
</html>
{% block js %}
{% endblock %}