src/flagging/urls.py
from django.conf.urls import url

# from . import views
from flagging.views import  flagging_app,login,media,action_plan,reports,techview,inspection
# from flagging.views import login
# import views.login
# import views.flagging_app
# import views.techview
# import views.inspection
# import views.media
# import views.action_plan
# import views.reports
# from flagging import views.login
urlpatterns = [
     url(r'^$', flagging_app.index, name='index'),
     url(r'^login/(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', login.loginview, name='login'),
    url(r'^login/$', login.loginview, name='login'),
    url(r'^logout/$', login.logoutview, name='logout'),
    url(r'^password/change$', login.passchange, name='passchange'),
    url(r'^password/create$', login.passcreate, name='passcreate'),
    url(r'^password/reset$', login.passreset, name='passreset'),
    url(r'^terms/$', login.terms, name='terms'),
    url(r'^username/reset$', login.userreset, name='userreset'),
    url(r'^firstlogin/$', login.firstlogin, name='firstlogin'),
    url(r'^newuser/$', login.newuser, name='newuser'),
    url(r'^tempnum/$', login.addTempNumber, name='tempnum'),
    url(r'^confirmation/$', login.confirmation, name='confirmation'),
    url(r'^ro_list/$', flagging_app.ro_list_ajax, name='ro_list'),
    url(r'^search_ros/$', flagging_app.search_ros_ajax, name='search_ros'),
    url(r'^update_flags/$', flagging_app.update_flags, name='update_flags'),
    url(r'^shop_notes/$', flagging_app.get_shop_notes, name='shop_notes'),
    url(r'^editro/$', flagging_app.editro, name='editro'),
    #     url(r'^shop_notes_ajax/$', views.flagging_app.get_shop_notes_by_filter, name='shop_notes_ajax'),
    url(r'^add_note/$', flagging_app.add_note, name='add_note'),
    url(r'^tech_view/$', techview.tech_view, name='tech_view'),
    url(r'^inspection/$', inspection.inspection, name='inspection'),
    url(r'^inspection/pdf$', inspection.get_results_summary_pdf, name='inspection_pdf'),
    url(r'^media/$', media.media, name='media'),
    url(r'^delete_media/$', media.delete_media, name='delete_media'),
    url(r'^result_summary/$', inspection.get_results_summary, name='result_summary'),
    url(r'^add_inspection_record/$', inspection.add_inspection_record, name='add_inspection_record'),
    url(r'^action_plan/$', action_plan.action_plan, name='action_plan'),
    url(r'^ro_details/$', flagging_app.get_ro_details_ajax, name='ro_details'),
    url(r'^reports/$', reports.get_reports, name='reports'),
    url(r'^reports/flag_analysis$', reports.get_shop_flag_report, name='flag_analysis'),
    url(r'^get_flag_notes$', flagging_app.get_flag_notes, name='get_flag_notes'),
    url(r'^add_recommendations$', flagging_app.add_recommendations, name='add_recommendations'),
    url(r'^inspection_test$', inspection.inspection_test, name='inspection_test'),
    url(r'^edit_recommendation', techview.edit_recommendation, name='edit_recommendation'),
    url(r'^mark_ro_complete', flagging_app.mark_as_complete, name='mark_ro_complete'),
    url(r'^get_repair_order_list', reports.get_repair_order_list, name='get_repair_order_list'),
    url(r'^pdfdev', action_plan.generate_pdf_view_debug, name='pdfdev'),
    url(r'^generatepdf', action_plan.generate_pdf_view, name='generatepdf'),
    url(r'^action_plan_pdf', action_plan.action_plan_pdf, name='action_plan_pdf'),
    url(r'^email_action_plan', action_plan.email_action_plan, name='email_action_plan'),
    url(r'^reports/generate_report$', reports.generate_report, name='generate_report'),
]

src/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'BMW.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^dealership/', include('dealership.urls', namespace="dealership")),
    url(r'^dealership/', include('dealership.urls', namespace='dealership' , app_name='dealership')),
    url(r'^livechat/', include('livechat.urls', namespace='livechat')),
    url(r'^customer/', include('customer.urls', namespace='customer')),
    url(r'^flagger/', include('flagging.urls', namespace='flagging')),
    url(r'^mobilecheckin/', include('mobilecheckin.urls', namespace='mobilecheckin' , app_name='mobilecheckin')),
    url(r'^admin/', include(admin.site.urls)),
#     url(r'^subview', include('subview.urls')),

# url(r'^oauth2/', include('oauth2_authentication.urls', namespace="oauth2"))

)
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

src/flagging/models.py
from django.db import models

# Create your models here.

src/dealership/forms.py
import re
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from dealership.models import *
from dealership.widgets import QuestionChoiceField



class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()



class LoginForm(forms.Form):
    username_attrs = {"required": True,
                      "placeholder":"Username",
                      "class":"form-control"
                      }
    password_attrs = {"required": True,
                      "placeholder":"Password",
                      "class":"form-control",
                    "max_length":30, "render_value":False
                      }
#     dict(=True, max_length=30,placeholder="abc","class"="")
    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(attrs=username_attrs), label=_("Username"), error_messages={ 'invalid': _("This value must contain only letters, numbers and underscores.") })
    password = forms.CharField(widget=forms.PasswordInput(attrs= password_attrs), label=_("Password"))
    remember = forms.BooleanField(required=False,initial=False,label='Extra cheeze')



class ChangePasswordForm(forms.Form):
    current_attrs = {"required": True,
                      "placeholder":"Enter Current Password",
                      "class":"form-control", "id":"current",
                      "max_length":30, "render_value":False
                      }
    new_attrs = {"required": True,
                      "placeholder":"Enter New Password",
                      "class":"form-control","id":"new",
                    "max_length":30, "render_value":False
                      }
    confirm_attrs = {"required": True,
                      "placeholder":"Confirm Password",
                      "class":"form-control","id":"confirm",
                    "max_length":30, "render_value":False
                      }
    current = forms.CharField(widget=forms.PasswordInput(attrs= current_attrs), label=_("Current"))
    new = forms.CharField(widget=forms.PasswordInput(attrs= new_attrs), label=_("New"))
    confirm = forms.CharField(widget=forms.PasswordInput(attrs= confirm_attrs), label=_("Confirm"))



class SecretQuestionForm(forms.Form):
    new_attrs = {"required": True,
                      "placeholder":"Enter New Password",
                      "class":"form-control","id":"new",
                    "max_length":30, "render_value":False
                      }
    confirm_attrs = {"required": True,
                      "placeholder":"Confirm Password",
                      "class":"form-control","id":"confirm",
                    "max_length":30, "render_value":False
                      }
    answer_attrs = {"required": True,
                      "placeholder":"Answer",
                      "class":"form-control","id":"answer",
                    "max_length":255, "render_value":False
                      }
    question_attrs = {"required": True,
                      "placeholder":"Question",
                      "class":"form-control","id":"question",
                    "render_value":False
                      }
    new = forms.CharField(widget=forms.PasswordInput(attrs= new_attrs), label=_("New"))
    confirm = forms.CharField(widget=forms.PasswordInput(attrs= confirm_attrs), label=_("Confirm"))
    questions = QuestionChoiceField(queryset=Questions.objects.all().order_by('id'),empty_label="Select a Question",widget=forms.Select(attrs=answer_attrs))
    answer = forms.CharField(widget=forms.TextInput(attrs=answer_attrs), label=_("Answer"))


class CreateUserForm(forms.Form):
    user_attrs = {"required": True,
                      "placeholder":"Enter your username",
                      "class":"form-control","id":"user_name_id","data-error":"false",
                    "max_length":30, "render_value":False
                      }
    profile_attrs = {"required": False,
                      "class":"form-control","id":"profile_user_id",
                    "max_length":30, "render_value":False
                      }
    new_attrs = {"required": True,
                      "placeholder":"Enter New Password",
                      "class":"form-control","id":"new",
                    "max_length":30, "render_value":False
                      }
    confirm_attrs = {"required": True,
                      "placeholder":"Confirm Password",
                      "class":"form-control","id":"confirm",
                    "max_length":30, "render_value":False
                      }

    username = forms.CharField(widget=forms.TextInput(attrs= user_attrs), label=_("User"))
    new = forms.CharField(widget=forms.PasswordInput(attrs= new_attrs), label=_("New"))
    confirm = forms.CharField(widget=forms.PasswordInput(attrs= confirm_attrs), label=_("Confirm"))
    profile = forms.CharField(widget=forms.HiddenInput(attrs= profile_attrs))

class CreatePasswordForm(forms.Form):
    new_attrs = {"required": True,
                      "placeholder":"Enter New Password",
                      "class":"form-control","id":"new",
                    "max_length":30, "render_value":False
                      }
    confirm_attrs = {"required": True,
                      "placeholder":"Confirm Password",
                      "class":"form-control","id":"confirm",
                    "max_length":30, "render_value":False
                      }
    answer_attrs = {"required": True,
                      "placeholder":"Answer",
                      "class":"form-control","id":"answer",
                    "max_length":255, "render_value":False
                      }
    new = forms.CharField(widget=forms.PasswordInput(attrs= new_attrs), label=_("New"))
    confirm = forms.CharField(widget=forms.PasswordInput(attrs= confirm_attrs), label=_("Confirm"))
    answer = forms.CharField(widget=forms.TextInput(attrs=answer_attrs), label=_("Answer"))

class UserPasswordResetForm(forms.Form):
    new_attrs = {"required": True,
                      "placeholder":"Enter New Password",
                      "class":"form-control","id":"new",
                    "max_length":30, "render_value":False
                      }
    confirm_attrs = {"required": True,
                      "placeholder":"Confirm Password",
                      "class":"form-control","id":"confirm",
                    "max_length":30, "render_value":False
                      }
#     answer_attrs = {"required": True,
#                       "placeholder":"Answer",
#                       "class":"form-control","id":"answer",
#                     "max_length":255, "render_value":False
#                       }
    new = forms.CharField(widget=forms.PasswordInput(attrs= new_attrs), label=_("New"))
    confirm = forms.CharField(widget=forms.PasswordInput(attrs= confirm_attrs), label=_("Confirm"))
#     answer = forms.CharField(widget=forms.TextInput(attrs=answer_attrs), label=_("Answer"))


class ResetForm(forms.Form):
    email_attrs = {"required": True,
                      "placeholder":"Email Address",
                      "class":"form-control","id":"email"
                      }

    email = forms.EmailField(widget=forms.TextInput(attrs=email_attrs), label=_("Email address"))
    #question_list = Questions.objects.values_list('id', 'question_text')
    #questions = forms.ChoiceField(choices=[(x, y) for x,y in question_list])

class SearchCustomerForm(forms.Form):
    CHOICES=[('name', 'Name'),
             ('phone', 'Phone #'),
             ('email', 'Email'),
             ('vin', 'VIN #'),
             ('appt', 'Appt. Confirmation #')]

    criteria_attrs = {"required": True,
                      "placeholder":"Enter Search Criteria",
                      "class":"form-control","id":"criteria"
                      }

    search_attrs = {"required": True
                      }

    search = forms.ChoiceField(choices=CHOICES, initial='name', widget=forms.RadioSelect(attrs=search_attrs))
    criteria = forms.CharField(widget=forms.TextInput(attrs=criteria_attrs), label=_("Criteria"))

"""    
class AddServiceRepairForm(forms.Form):
    CHOICES=[('r', 'Repair'),
             ('s', 'Service')]
    
    type_attrs = {"required": True,
                      "class":"form-control form-service-type"
                      }
    
    id_attrs = {"required": False,
                      "class":"form-control form-service-id"
                      }
    
    name_attrs = {"required": True,
                      "class":"form-control form-service-name", "placeholder":"Enter Service Name"
                      } 
    
    code_attrs = {"required": True,
                      "class":"form-control form-service-code", "placeholder":"Enter DMS OpCode"
                      }
    
    duration_attrs = {"required": True,
                      "class":"form-control form-service-duration", "placeholder":"Enter Duration of Service"
                      }
    
    price_attrs = {"required": True,
                      "class":"form-control form-service-price", "placeholder":"Enter Price of Service"
                      }
   
    flag_attrs = {"required": False,
                      "class":"form-control form-service-flag",
                      "value":0
                      } 
    desc_attrs = {"required": True,
                      "class":"form-control form-service-desc", "rows":4,
                      "placeholder":"This is the description that will display for the customer. Edit description here"
                      }
    
    id = forms.CharField(widget=forms.HiddenInput(attrs=id_attrs)) 
    type = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect(attrs=type_attrs))
    name = forms.CharField(widget=forms.TextInput(attrs=name_attrs), label=_("Name"))
    dms_opcode = forms.CharField(widget=forms.TextInput(attrs=code_attrs), label=_("DMS OpCode"))

src/flagging/forms.py
'''
Created on Nov 20, 2015

@author: mjnasir

'''
from django import forms
from django.forms.models import ModelForm
from django.utils.translation import ugettext_lazy as _
from dealership.models import UserProfile



class NewUserEmailForm(forms.Form):
    email_attrs = {"required": True,
                      "placeholder":"Email Address",
                      "class":"form-control","id":"email"
                      }

    email = forms.EmailField(widget=forms.TextInput(attrs=email_attrs), label=("Email address"))

class TempNumberForm(forms.Form):
    number_attrs = {"required": True,
                    "placeholder" : "Phone Number",
                    "class": "form-control","id":"number"
                    }
    number = forms.IntegerField(widget=forms.TextInput(attrs=number_attrs),label=("Phone Number"))

class UpdateRODetails(forms.Form):
    number_attrs = {"required": True,
                    "placeholder" : "RO Number",
                    "class": "form-control",
                    "id":"roedit_number"
                    }
    rfid_attrs = {"required": True,
                    "placeholder" : "RFID Tag",
                    "class": "form-control",
                    "id":"roedit_rfid"
                    }
    roedit_number = forms.CharField(widget=forms.TextInput(attrs=number_attrs),label=("RO Number"))
    roedit_rfid = forms.CharField(widget=forms.TextInput(attrs=rfid_attrs),label=("RFID Tag"))


class SkipConfirmationForm(forms.Form):
    skip = forms.BooleanField(required=False,initial=False,label='skip')

class UpdateNumberOrEmailForm(forms.Form):
    field_attrs = {"required": True,
                    "class": "form-control","id":"modeId",
                    "placeholder":"Phone Number"
                    }
    field = forms.CharField(widget=forms.TextInput(attrs=field_attrs), label=_("field"))

src/flagging/views/media.py
'''
Created on Jan 5, 2016

@author: mjnasir
'''


from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render

from dealership.models import RoInspection
from flagging.services.RoServices import RoServices
#from flagging.factory import RoServicesFactory


def media(request):
    params = {}
    if request.method == "GET":
        if "roNumber" in request.GET :
            roNumber = request.GET.get("roNumber")
            roService = RoServices(request.session["dealer_id"])
            params["roDetails"] = roService.getROdetails(roNumber)
            params["color"] = roService.getColorForRO(roNumber)
            params["images"] = roService.getImagesByRoNumber(roNumber)
            params["walkArounds"] = roService.getWalkAroundImages(roNumber)
            params["roNumber"] = roNumber
            params["roID"] = roService.getROId(roNumber)

    return render(request,"flagging_app/media.html",params)


def delete_media(request):
    if request.method == "GET":

        roService = RoServices()
        roService.deleteImage(request)
        return HttpResponseRedirect( reverse('flagging:media')+"?roNumber=" +request.GET.get("roNumber") )

src/flagging/templates/flagging/confirmation.html
{% extends 'flagging/base.html' %}
{% block main %}
<div class="container-fluid">
	<div class="row">
    	<div class="col-sm-offset-2 col-sm-8">
            <h3 class="font_regular">Hello {{ userProfile.user.first_name }} {{ userProfile.user.last_name }}</h3>
            <p>If you would like to recieve alerts when flags are update. Please select by TEXT or by EMAIL bellow:</p>
            <div class="clear pad-10"></div>
            <div class="radio" style="margin-top:-5px;">
            	<label><input type="radio" name="mode" checked value="text"> <span>By Text</span></label></br>
            	<label><input type="radio" name="mode" value="email"> <span>By email</span></label>
            </div>
            
            	
            
            <div class="clear pad-10"></div>
            <div class="well" id="phoneNumber" >
                <p>This is the number we have on file for you. Is this the mobile number you would like alerts sent for you?</p>                
                <p><strong>{{ userProfile.phone_number }}</strong></p>
                <p>If you would like to use different number please enter it here.</p>
                <form class="form-inline" action="{% url 'flagging:confirmation' %}" method="post">
                	<div class="form-group col-sm-4">
                	{% csrf_token %}
                    	{{ form.field }}
                    	<input type = "hidden" value="text" name = "modeType">
  					</div>
                    <button type="submit" class="btn btn-info">Submit Number</button>
				</form>
            </div>
            <div class="well" id = "email" style="display:None">
                <p>This is the email we have on file for you. Is this the email you would like alerts sent for you?</p>                
                <p><strong>{{ userProfile.user.email }}</strong></p>
                <p>If you would like to use different email please enter it here.</p>
                <form class="form-inline" action="{% url 'flagging:confirmation' %}" method="post">
                	<div class="form-group col-sm-4">
                	{% csrf_token %}		
                    	{{ form.field }}
                    	<input type = "hidden" value="email" name = "modeType">
  					</div>
                    <button type="submit" class="btn btn-info">Submit Email</button>
				</form>
            </div>
            <form action="{% url 'flagging:confirmation' %}" method="post">
            {% csrf_token %}
            <div class="radio pull-right">
                <label><input type="checkbox" id="isSkip" > <span>Please don`t show this screen again</span></label>
            </div>
            <input type="hidden" name="modeType" value="skip" >
            <input type="hidden" name="is_skip_hidden" id = "is_skip_hidden" value="false" >
            <div class="clear pad-10"></div>
            <p class="text-right"><button type="submit" class="btn btn-info">Skip</button></p>
        	</form>
        </div>
    </div>
</div>
<div class="clear pad-5"></div>
{% endblock %}
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block script %}
<script>
$(document).ready(function(){
	
	$("#isSkip").change(function(){
		$("#is_skip_hidden").val($("#isSkip").is(":checked"));
		
	});
	$("input[name=mode]:radio").change(function (){

		var val = $('input[name=mode]:checked').val();
		if (val == "email"){
			$("input[name=field]").attr("placeholder","Email");
			$("#phoneNumber").hide();
			$("#email").show();
		}else if (val == "text"){
			$("input[name=field]").attr("placeholder","Phone Number");
			$("#phoneNumber").show();
			$("#email").hide();
		}
		


		});
});

</script>

{% endblock %}

src/flagging/templates/flagging/index.html
{% extends 'flagging/base.html' %}
{% block main %}
<a href="{% url 'flagging:logout' %}">Logout</a>
{% endblock %}

src/flagging/templates/flagging/login.html
{% extends 'flagging/base.html' %}
{% block main %}
<div class="clear pad-50"></div>
<div class="container-fluid">
	<div class="row">
    	<div class="col-sm-offset-3 col-sm-6">
            <div class="LoginBox">
            	<h3 class="mt-0 text-center">Login to <strong>Flagger</strong></h3>
                <hr>
                <div class="error">
                {% if  form.non_field_errors %}
				        	 <div class="alert error alert-danger fade in">
						    	<a href="#" class="close" data-dismiss="alert">&times;</a>
						    	<strong>Error!</strong>{{ form.non_field_errors }}
								</div>
								{%endif%}
                </div>
	            
	              {% if user.is_authenticated %}
	                <div class="clear pad-5"></div>
	                <p>User <strong>{{ user.userprofile.first_name }} {{ user.userprofile.last_name }}</strong> is currently logged in.<a href="{% url 'flagging:logout' %}">Click here</a> to log them out</p>
	              {% else %}
	            
                <form action="{% url 'flagging:login' %}" method="post">
                	{% csrf_token %}
                	<div class="form-group">
                		{% if  form.username.errors %}
					        	 <div class="alert error alert-danger fade in">
								    	<a href="#" class="close" data-dismiss="alert">&times;</a>
						    	    <strong>Error!</strong>{{ form.username.errors }}
										</div>
										{%endif%}
                    	
                    	{{ form.username }}
                        <p class="text-right"><small><a href="{% url 'flagging:userreset' %}">Forgot Username?</a></small></p>
  					</div>
  					<div class="form-group">
                    	<!--  <input type="password" class="form-control" id="" name="password" placeholder="Password">-->
                    	{{ form.password }}
                        <p class="text-right"><small><a href="{% url 'flagging:passreset' %}">Forgot Password?</a></small></p>
  					</div>
                    <div class="checkbox-inline no_indent">
	                      <input class="form-check-input position-static" type="checkbox" id="id_remember" value="{{form.instance.remember}}">
	                      <span  class="mr-10">Keep me logged in </span>
                    </div>
                    
                    <input type="hidden" id= "dealer_code" name="dealer_code" value = "{{ dealer_code }}">
                    <div class="clear pad-5"></div>
                    <button type="submit" class="btn btn-info">Submit</button>
	                

	                
				</form>
			            <div class="clear pad-10"></div>
	                <hr>
	                <p class="mt-0 text-larger"><a href="{%url 'dealership:login'%}?dealer_code={{dealer_code}}">Login</a> to the <strong>Dealership</strong> app instead</p>
	                <p class="mt-0text-larger"><a href="{%url 'mobilecheckin:login'%}?dealer_code={{dealer_code}}">Login</a> to the <strong>Mobile Checkin</strong> app instead</p>

	       
								{% endif %}
            </div>
        </div>
    </div>
</div>
<div class="clear pad-5"></div>
{% endblock %}

src/flagging/templates/flagging/password_create.html
{% extends 'flagging/password_base.html' %}
{% block title %}
<h3 class="font_regular">Create New Password</h3>
{% endblock %}

{% block fields %}
<div class="col-sm-9">
<p>Please enter a new password that you will remember. The password must be at least six characters with at least one upper case character, one lower case character, one number and one symbol.</p>

	<form id="form_pass" action="{% url 'flagging:passcreate' %}?token={{ token }}" method="post">
		{% csrf_token %}
	    <div class="form-group">
	    	{{ form.new }}
	        <!-- <input type="password" class="form-control" id="new" placeholder="Enter New Password"> -->
	    </div>
	    <div class="form-group">
	    	{{ form.confirm }}
	        <!-- <input type="password" class="form-control" id="confirm" placeholder="Confirm Password"> -->
	    </div>
	    
	    <div class="form-group">
	    	<label>{{ question }}</label>
	    </div>
	    
	    <div class="form-group">
	    	{% if  form.answer.errors %}
	        	 <div class="alert error alert-danger fade in">
			    	<a href="#" class="close" data-dismiss="alert">&times;</a>
			    	<strong>Error!</strong>{{ form.answer.errors }}
				</div>
			{%endif%}
	    	{{ form.answer }}
	    </div>
	    <div class="clear pad-5"></div>
	    <button type="submit" class="btn btn-info">Ok</button> &nbsp;
	    <a href="{% url 'flagging:index' %}" class="btn btn-grey">Cancel</a>
	</form>

</div>
{% endblock %}
<script>
$(document).ready(function(){
	$('#form_pass #new').focusout(function(){
		alert("geg");
		console.info($(this).val().length);
		
		if($(this).val().length > 5) { $(".tick #char").addClass("check"); }
		else { $(".tick #char").removeClass("check") }
		
		if($(this).val().match(/[A-Z]/)){$(".tick #uper").addClass("check"); }
		else {$(".tick #uper").removeClass("check")}
		
		if($(this).val().match(/[a-z]/)){$(".tick #lower").addClass("check"); }
		else {$(".tick #lower").removeClass("check")}
		
		if($(this).val().match(/[0-9]/)){$(".tick #number").addClass("check"); }
		else {$(".tick #number").removeClass("check")}
		
		if($(this).val().match(/[!@#$%^&*()+=\';,.\/{}|":<>?~_-]/)){$(".tick #symbol").addClass("check"); }
		else {$(".tick #symbol").removeClass("check")}
		
		if($(this).val() == $('#form_pass #confirm').val()){ $(".tick #match").addClass("check") ; }
		else { $(".tick #match").removeClass("check") }
	});
 
	$('#form_pass #confirm').focusout(function(){
		if($(this).val() == $('#form_pass #new').val()){ $(".tick #match").addClass("check") ; }
		else { $(".tick #match").removeClass("check") }
	});
	
	$('#form_pass').submit(function(event){
		if($('.tick .check').size() < 6){
			event.preventDefault();
		}
	});
});
</script>

src/flagging/templates/flagging/password_reset.html
{% extends 'flagging/base.html' %}
{% block main %}
<div class="clear pad-50"></div>
<div class="container-fluid">
	<div class="row">
    	<div class="col-sm-offset-3 col-sm-6">
            <div class="well">
            	<h3 class="mt-0 text-center">Reset Password</h3>
                <p>Please enter the email associated with your Dealership account and we will send instructions.</p>
                <form action="{% url 'flagging:passreset' %}" method="post"> 
                	{% csrf_token %}
                	<div class="form-group">
                		
                		{% if  form.email.errors %}
				        	 <div class="alert error alert-danger fade in">
						    	<a href="#" class="close" data-dismiss="alert">&times;</a>
						    	<strong>Error!</strong>{{ form.email.errors }}
							</div>
						{%endif%}
                		{{ form.email }}
                    	<!-- <input type="email" class="form-control" id="" placeholder="c"> -->
  					</div>  					
                    <div class="clear pad-5"></div>
                    <button type="submit" class="btn btn-info">Ok</button> &nbsp; 
                    <a href="{% url 'flagging:index' %}" class="btn btn-grey">Cancel</a>
				</form>
            </div>
        </div>
    </div>
</div>
<div class="clear pad-5"></div>
{% endblock %}

src/flagging/templates/flagging/username_reset.html
{% extends 'flagging/base.html' %}
{% block main %}
<div class="clear pad-50"></div>
<div class="container-fluid">
	<div class="row">
    	<div class="col-sm-offset-3 col-sm-6">
            <div class="LoginBox">
            	<h3 class="mt-0 text-center">Reset Username</h3>
                <p>Please enter the email associated with your Flagging account and we will send instructions.</p>
                <form action="{% url 'flagging:userreset' %}" method="post"> 
                	{% csrf_token %}
                	<div class="form-group">
                		{{ form.email.errors }}
                		{{ form.email }}
                    	<!-- <input type="email" class="form-control" id="" placeholder="c"> -->
  					</div>  					
                    <div class="clear pad-5"></div>
                    <button type="submit" class="btn btn-info">Ok</button> &nbsp; 
                    <a href="{% url 'flagging:index' %}" class="btn btn-grey">Cancel</a>
				</form>
            </div>
        </div>
    </div>
</div>
<div class="clear pad-5"></div>
{% endblock %}