src/customer/urls.py
from django.conf.urls import url

from customer.views import login, main, vehicle, account, notifications, appoint, service , statusalert,cart


urlpatterns = [
    url(r'^$', login.login, name='index'),
#     url(r'^import_csv$', login.import_csv, name='index'),
    url(r'pull_models', login.pull_models, name='pull_models'),
    url(r'create_models', login.create_models, name='create_models'),
    url(r'delete_models', login.delete_models, name='delete_models'),
    url(r'create_models', login.create_models, name='create_models'),
    url(r'^login/(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', login.login, name='login'),
    url(r'^login/?$', login.login, name='login'),
    url(r'^password/reset/$', login.passreset, name='passreset'),
    url(r'^username/reset/$', login.userreset, name='userreset'),
    url(r'^password/create$', login.passcreate, name='passcreate'),
    url(r'^main/$', vehicle.mainview , name='main'),
    url(r'^accountsettings/$', account.accountview , name='accountsettings'),
    url(r'^logout/$', login.logout, name='logout'),
    url(r'^test_ocr/$', main.test_ocr, name='test_ocr'),
    url(r'^puller/$', main.test_puller, name='puller'),
    url(r'^vehiclewidget/$', vehicle.get_vehicle, name='vehiclewidget'),
    url(r'^delete_vehicle/$', vehicle.del_vehicle, name='del_vehicle'),
    url(r'^ocr_snap/$', vehicle.ocr_snap, name='ocr_snap'),
    url(r'^delete_account/$', account.delete, name='delete_account'),
    url(r'^notifications/$', notifications.notificationssettings, name='notifications'),
    url(r'^findapp/$', appoint.find_exiting_appointment, name='findapp'),
    url(r'^search_app/$', appoint.search_app, name='search_app'),#used for searching thourhg ajax
    url(r'^new_customer_vehicle/$', login.new_customer_vehicle, name='new_customer_vehicle'),
    url(r'^vehicle_selection_appointment/$', appoint.vehicle_selection, name='vehicle_selection_appointment'),
    url(r'^service_selection_appointment/$', appoint.service_selection_appointment, name='service_selection_appointment'),
    url(r'^date_selection_appointment/$', appoint.date_selection_appointment, name='date_selection_appointment'),
    url(r'^get_all_services_ajax/$', service.get_all_services, name='get_all_services_ajax'),
    url(r'^save_appointment_services_ajax/$', service.save_all_services, name='save_appointment_services_ajax'),
    url(r'^get_all_advisors_ajax/$', service.get_all_advisor, name='get_all_advisors_ajax'),
    url(r'^save_advisor_ajax/$', service.save_advisor, name='save_advisor_ajax'),
    url(r'^schedule_appointment/$', appoint.schedule_appointment, name='schedule_appointment'),
    url(r'^cancel_appointment/$', appoint.cancel_appointment, name='cancel_appointment'),
     url(r'^search_by_code_phone/$', appoint.search_by_code_phone, name='search_by_code_phone'),
     url(r'^book_appointment/$', appoint.book_appointment, name='book_appointment'),
     url(r'^check_username_exist/$', login.check_username, name='check_username'),
    url(r'^createuser/$', login.createuser, name='createuser'),
     url(r'^registeruser/$', login.registeruser, name='registeruser'),
    url(r'^sendemail/$', appoint.sendemail, name='sendemail'),
    url(r'^testingurl/$', login.testing, name='testingurl'),
     url(r'^uploadvin/$', appoint.uploadvin, name='uploadvin'),
     url(r'^book_appointment_now_new/$', appoint.book_appointment_now_new, name='book_appointment_now_new'),
     url(r'^book_appointment_now_existing/$', appoint.book_appointment_now_existing, name='book_appointment_now_ext'),
      url(r'^get_available_slabs_for_date/$', appoint.get_available_slabs_for_date, name='get_available_slabs_for_date'),
      url(r'^check_userprofile/$', appoint.check_userprofile, name='check_userprofile'),
      url(r'^get_available_adivsors_for_date/$', appoint.get_available_adivsors_for_date, name='get_available_adivsors_for_date'),
      url(r'^save_appointment_now_ext/$', appoint.save_appointment_now_ext, name='save_appointment_now_ext'),
      # url(r'^statusalert/(?P<appointment_id>\d+)/$', statusalert.index, name='status_alert_index'),
      url(r'^statusalert/(?P<appointment_hash>[0-9A-F]{56})/$', statusalert.index_hash, name='status_alert_index_hash'),

    url(r'^approvestatus/(?P<appointment_id>\d+)/$', statusalert.approve_recommendations, name='approve_status'),

       url(r'^replystatus/(?P<appointment_id>\d+)/$', statusalert.reply, name='reply_status'),

        url(r'^getcart/$', cart.get_cart, name='getcart'),
    url(r'^send_activation_code/$', service.send_activation_code, name='send_activation_code'),
     url(r'^save_customer_number/$', service.save_customer_number, name='save_customer_number'),

       url(r'^paymentstatus/(?P<appointment_id>\d+)/$', statusalert.payment, name='payment_status'),
       url(r'^getcart/$', cart.get_cart, name='getcart'),
        url(r'^download_calendar/$', appoint.download_calendar, name='download_calendar'),
        url(r'^sync_gcalendar/$', login.sync_gcalendar, name='sync_gcalendar'),

        url(r'oauth2callback', login.auth_return, name='return'),
        url(r'print_appointment', appoint.print_appointment, name='print_appointment'),
        url(r'^service_history/(?P<vehicle_id>[a-zA-Z0-9_-]+)/?$', vehicle.service_history, name='service_history'),
         url(r'^(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', login.index, name='index'),



]

src/dealership/urls.py
from django.conf.urls import url

from dealership import views

import views.login
import views.chat
from views.overview import *
from views.appointment import *
from views.customers import *
from views.rservices import *
from views.notifications import *
from views.sms_reply import *
from views.manage import *

urlpatterns = [
    #url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^$', views.login.index, name='index'),
    url(r'delete_models', views.manage.delete_models, name='delete_models'),
    url(r'create_models', views.manage.create_models, name='create_models'),
    url(r'select_makes', views.manage.select_makes, name='select_makes'),
    url(r'^login/(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', views.login.loginview, name='login'),
    url(r'^login/$', views.login.loginview, name='login'),
    url(r'^logout/$', views.login.logoutview, name='logout'),
    url(r'^request/$', views.login.requestview, name='request'),
    url(r'^password/change$', views.login.passchange, name='passchange'),
    url(r'^password/create$', views.login.passcreate, name='passcreate'),
    url(r'^password/reset$', views.login.passreset, name='passreset'),
    url(r'^username/reset$', views.login.userreset, name='userreset'),
    url(r'^terms/$', views.login.terms, name='terms'),
    url(r'^firstlogin/$', views.login.firstlogin, name='firstlogin'),
    #chat
    url(r'^chats/$', views.chat.chats, name='chats'),
    url(r'^chat/$', views.chat.chat, name='chat'),

    url(r'^getnotifications/$', views.notifications.get_live_notifications, name='get_notifications'),
    url(r'^resetnotifications/$', views.notifications.reset_live_notifications, name='reset_notifications'),

    url(r'^smsreply/$', views.sms_reply.SMSReply.as_view(), name='sms_reply'),

    #overview
    url(r'^overview/$', views.overview.overview, name='overview'),
    #url(r'^overview/time/daily$', views.overview.ov_time_daily, name='ov_time_daily'),
    url(r'^overview/daily$', views.overview.ov_time_daily, name='ov_time_daily'),
    #url(r'^overview/advisor/daily$', views.overview.ov_adv_daily, name='ov_adv_daily'),
    #url(r'^overview/status/daily$', views.overview.ov_status_daily, name='ov_status_daily'),
    #url(r'^overview/time/weekly$', views.overview.ov_time_weekly, name='ov_time_weekly'),
    url(r'^overview/weekly$', views.overview.ov_time_weekly, name='ov_time_weekly'),
    #url(r'^overview/advisor/weekly$', views.overview.ov_adv_weekly, name='ov_adv_weekly'),
    #url(r'^overview/status/weekly$', views.overview.ov_status_weekly, name='ov_status_weekly'),
    #overview_ajax
    url(r'^overview/wallboard$', views.overview.wallboard_ajax_view, name='wallboard'),
    url(r'^overview/searchcustomer$', views.overview.searchcustomer_ajax_view, name='searchcustomer'),
    url(r'^overview/time/daily/slab$', views.overview.dailyapt_ajax_view, name='ov_time_daily_slab'),
    url(r'^overview/time/daily/search$', views.overview.time_daily_search_ajax_view, name='ov_time_daily_search'),
    url(r'^overview/time/daily/appt$', views.overview.time_daily_search_appt_ajax_view, name='ov_time_daily_search_appt'),
    url(r'^overview/time/daily/row$', views.overview.appointment_row_ajax_view, name='ov_time_daily_row'),
    url(r'^overview/time/weekly/day$', views.overview.time_weekly_day_ajax_view, name='ov_time_weekly_day'),
    url(r'^overview/time/weekly/slab$', views.overview.time_weekly_slab_ajax_view, name='ov_time_weekly_slab'),
    url(r'^overview/daily/advisor$', views.overview.advisor_ajax_view, name='ov_daily_advisor'),
    url(r'^overview/daily/advisor/slab$', views.overview.advisor_daily_slab_ajax_view, name='ov_advisor_daily_slab'),
    url(r'^overview/weekly/advisor/slab$', views.overview.advisor_weekly_slab_ajax_view, name='ov_advisor_weekly_slab'),
    url(r'^overview/daily/status$', views.overview.status_ajax_view, name='ov_daily_status'),
    url(r'^overview/daily/wayaway$', views.overview.wayaway_ajax_view, name='ov_daily_wayaway'),
    url(r'^overview/daily/status/slab$', views.overview.status_daily_slab_ajax_view, name='ov_status_daily_slab'),
    url(r'^overview/weekly/status/slab$', views.overview.status_weekly_slab_ajax_view, name='ov_status_weekly_slab'),
    url(r'^overview/appointment/detail$', views.overview.appointment_detail_ajax_view, name='ov_appointment_detail'),
    url(r'^overview/update/creaditcard$', views.overview.appointment_update_creditcard, name='ov_update_cc'),
    url(r'^overview/update/updateodoout$', views.overview.appointment_update_odoout, name='ov_update_odoout'),
    url(r'^overview/update/vehicle$', views.overview.appointment_update_vehicle, name='ov_update_vehicle'),
    url(r'^overview/update/insurance$', views.overview.appointment_update_insurance, name='ov_update_insurance'),
    #appointment
    url(r'^appointment/$', views.appointment.appointment, name='appointment'),
    url(r'^appointment/create/update', views.appointment.appointment_create_update, name='appointment_create_update'),
    url(r'^appointment/customer$', views.appointment.appointment_customer_ajax_view, name='appointment_customer'),
    url(r'^appointment/customer/vehicle/delete$', views.appointment.customer_delete_vehicle_ajax_view, name='appointment_customer_vehicle_delete'),
    url(r'^appointment/update/time$', views.appointment.appointment_time_ajax_view, name='appointment_update_time'),
    url(r'^appointment/wayaway$', views.appointment.appointment_wayaway_ajax_view, name='appointment_wayaway'),
    url(r'^appointment/wayaway/save$', views.appointment.appointment_wayaway_save_ajax, name='appointment_wayaway_save'),
    url(r'^appointment/repair$', views.appointment.appointment_repair_ajax_view, name='appointment_repair'),
    url(r'^appointment/accountinfo$', views.appointment.appointment_account_info_ajax_view, name='appointment_accountinfo'),
    url(r'^appointment/book', views.appointment.appointment_book_ajax_view, name='appointment_book'),
    url(r'^appointment/remove/service', views.appointment.appointment_remove_service, name='appointment_remove_service'),

    #customers
    url(r'^customers/$', views.customers.customers, name='customers'),
    url(r'^customers/add/user$', views.customers.save_customer_ajax, name='customers_add_user'),
    url(r'^customers/add/vehicle$', views.customers.save_vehicle_ajax, name='customers_add_vehicle'),
    url(r'^customers/add/appointment$', views.customers.save_appointment_ajax, name='customers_add_appointment'),
    url(r'^customers/add/reminder', views.customers.save_guest_reminder_ajax, name='customers_add_reminder'),
    #repair and servicea
    url(r'^rservices/$', views.rservices.rservices, name='rservices'),
    url(r'^rservices/form$', views.rservices.get_rservices_form, name='rservices_form'),
    url(r'^rservices/create/update', views.rservices.rservices_create_update, name='rservices_create_update'),
    url(r'^rservices/delete', views.rservices.rservices_delete, name='rservices_delete'),
    #dealership_manage
    url(r'^manage/$', views.manage.manage, name='manage'),
    url(r'^manage/deatil$', views.manage.details, name='manage_details'),
    url(r'^manage/user_term_advisor$', views.manage.add_user_advisor, name='add_user_advisor'),
    url(r'^manage/add_amenities$', views.manage.add_amenities, name='add_amenities'),
    url(r'^manage/delete_amenities$', views.manage.delete_amenities, name='delete_amenities'),
    url(r'^manage/get_resource_link$', views.manage.get_resource_link, name='get_resource_link'),
    url(r'^manage/add_resource_link$', views.manage.add_resource_link, name='add_resource_link'),
    url(r'^manage/delete_resource_link$', views.manage.delete_resource_link, name='delete_resource_link'),
    url(r'^manage/update_resource_link$', views.manage.update_resource_link, name='update_resource_link'),
    url(r'^manage/get_shopcontacts$', views.manage.get_shopcontacts, name='get_shopcontacts'),
    url(r'^manage/add_shopcontacts$', views.manage.add_shopcontacts, name='add_shopcontacts'),
    url(r'^manage/delete_shopcontacts$', views.manage.delete_shopcontacts, name='delete_shopcontacts'),
    url(r'^manage/update_shopcontacts$', views.manage.update_shopcontacts, name='update_shopcontacts'),
    url(r'^manage/get_marketing$', views.manage.get_marketing, name='get_marketing'),
    url(r'^manage/add_marketing$', views.manage.add_marketing, name='add_marketing'),
    url(r'^manage/get_feedback$', views.manage.get_feedback, name='get_feedback'),
    url(r'^manage/add_feedback$', views.manage.add_feedback, name='add_feedback'),
    url(r'^manage/get_serviceemail$', views.manage.get_serviceemail, name='get_serviceemail'),
    url(r'^manage/add_serviceemail$', views.manage.add_serviceemail, name='add_serviceemail'),
    url(r'^manage/delete_email$', views.manage.delete_email, name='delete_email'),
    url(r'^manage/update_email$', views.manage.update_email, name='update_email'),
    url(r'^manage/get_sms$', views.manage.get_sms, name='get_sms'),
    url(r'^manage/add_sms$', views.manage.add_sms, name='add_sms'),
    url(r'^manage/delete_sms$', views.manage.delete_sms, name='delete_sms'),
    url(r'^manage/update_sms$', views.manage.update_sms, name='update_sms'),
    url(r'^manage/get_shphr$', views.manage.get_shophrs, name='get_shophrs'),
    url(r'^manage/add_shphr$', views.manage.add_shophrs, name='add_shophrs'),
    url(r'^manage/delete_shphr$', views.manage.delete_shophrs, name='delete_shophrs'),
    url(r'^manage/update_shphr$', views.manage.update_shophrs, name='update_shophrs'),
    url(r'^manage/get_holidays$', views.manage.get_holidays, name='get_holidays'),
    url(r'^manage/add_holiday$', views.manage.add_holiday, name='add_holiday'),
    url(r'^manage/delete_holiday$', views.manage.delete_holiday, name='delete_holiday'),
    url(r'^manage/update_holiday$', views.manage.update_holiday, name='update_holiday'),
    url(r'^manage/get_uaform$', views.manage.get_user_advisor_form, name='get_uaform'),

src/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'BMW.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^dealership/', include('dealership.urls', namespace="dealership")),
    url(r'^dealership/', include('dealership.urls', namespace='dealership' , app_name='dealership')),
    url(r'^livechat/', include('livechat.urls', namespace='livechat')),
    url(r'^customer/', include('customer.urls', namespace='customer')),
    url(r'^flagger/', include('flagging.urls', namespace='flagging')),
    url(r'^mobilecheckin/', include('mobilecheckin.urls', namespace='mobilecheckin' , app_name='mobilecheckin')),
    url(r'^admin/', include(admin.site.urls)),
#     url(r'^subview', include('subview.urls')),

# url(r'^oauth2/', include('oauth2_authentication.urls', namespace="oauth2"))

)
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

src/customer/models.py
from django.contrib.auth.models import User
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.db import models
from oauth2client.contrib.django_orm import FlowField, CredentialsField

from dealership.models import Questions, Appointment


class FlowModel(models.Model):
    id = models.OneToOneField(Appointment, primary_key=True)
    flow = FlowField()


class CredentialsModel(models.Model):
    id = models.OneToOneField(Appointment, primary_key=True)
    credential = CredentialsField()

src/customer/views/paypal_execute.py
import paypalrestsdk
import logging
logging.basicConfig(level=logging.INFO)

# ID of the payment. This ID is provided when creating payment.
payment = paypalrestsdk.Payment.find("PAY-28103131SP722473WKFD7VGQ")

# PayerID is required to approve the payment.
if payment.execute({"payer_id": "DUFRQ8GWYMJXC"}):  # return True or False
    print("Payment[%s] execute successfully" % (payment.id))
else:
    print(payment.error)

src/customer/templates/customer/appointment/date_advisor_selection.html
{% extends "customer/layouts/appointment_base.html" %}
{% load staticfiles i18n %}
{% block submain%}
		{%if appointment %}
	<ul id="myTabs" class="service_menu ">
	        	<li role="dropdown" class="dropdown dropdown-hover ">
		            	<a href="{% url 'customer:vehicle_selection_appointment' %}?dealer_code={{dealer_code}}&appointment_id={{appointment.id}}" id="vehicles-tab">Vehicles</a>
		            	<ul class="dropdown-menu" style="display: none;width:100%">
		           			 <li>
		           			 		{%if appointment.vehicle%}
		           			 			{{appointment.vehicle.vehicle.make.name}} {{appointment.vehicle.vehicle.model.name}}
		           			 		{%else%}
		           			 			Please select a vehicle
		           			 		{%endif%}
		           			 </li>
		     		   </ul>
          		  </li>
          		  
	            <li role="dropdown"  class="dropdown dropdown-hover ">
	          	  
	            	  <a href="{% url 'customer:service_selection_appointment' %}?dealer_code={{dealer_code}}&appointment_id={{appointment.id}}">Service and Repair </a>
            		<ul class="dropdown-menu" style="display: none;width:100%">
	            		<li>
	            				<div id="service_repair_top_bar" >
	            						
	            						{%if services_list  %}
	            							Services and Repairs Added
	            						{%else%}
	            							No Service or Repair Added
	            						{%endif%}
		           			 		
		           			 	</div>
		           			 </li>
		           	</ul>
	            </li>
	            
	            <li role="dropdown" class="dropdown dropdown-hover active">
	            	
	            	 <a href="{% url 'customer:date_selection_appointment' %}?dealer_code={{dealer_code}}&appointment_id={{appointment.id}}">Appointment</a>
	            	<ul class="dropdown-menu" style="display: none;width:100%">
	            		<li>
	            				<div id="date_adv_top_bar" >
		           			 		{%if appointment.advisor or appointment.start_time  or appointment.way_away %}
		           			 			{%if appointment.start_time%}
		           			 				Date time{%if appointment.start_time or appointment.way_away%},
		           			 				{%endif%}
		           			 			{%endif%}
		           			 			{%if appointment.advisor%}
		           			 				&nbsp;Advisor
		           			 				{%if appointment.way_away%},
		           			 				{%endif%}
		           			 			{%endif%}
		           			 			{%if appointment.way_away%}
		           			 			&nbsp;Way away
		           			 			{%endif%}
		           			 			selected
		           			 		{%else%}
		           			 			Select Date, Advisor, Way away
		           			 		{%endif%}
		           			 	</div>
		           			 </li>
		           	</ul>
	            </li>
	            <li role="dropdown" class="dropdown dropdown-hover">
	            	
	            	 <a href="{% url 'customer:book_appointment' %}?dealer_code={{dealer_code}}&appointment_id={{appointment.id}}">Review and Book</a>
	            	<ul class="dropdown-menu" style="display: none;width:100%">
	            		<li>
	            				<div id="book_top_bar" >
		           			 		Complete Previous Steps
		           			 	</div>
		           			 </li>
		           	</ul>
	            </li>
	</ul>
	<div class="pad-10"></div>
	
{%endif%}
	 <ul class="pager">
		 		<li class="previous pointer">
		 					 <a data-href="{% url 'customer:service_selection_appointment' %}?dealer_code={{dealer_code}}&appointment_id={{appointment.id}}&accordion=repairs" >
		 						<span aria-hidden="true">←</span> Previous</a>
		 						</li>
		   		<li class="next pointer" id="submit_btn">
		   				<a data-href="{% url 'customer:book_appointment' %}?dealer_code={{dealer_code}}&appointment_id={{appointment.id}}">
		   				
		   				Next <span aria-hidden="true">→</span></a>
		   		</li>
  	</ul>
      <div class="panel-group" id="accordion2" role="tablist" aria-multiselectable="true">
      				{%include 'customer/appointment/partials/advisor_selection.html' %}
      				{%include 'customer/appointment/partials/way_away.html' %}
      				{%include 'customer/appointment/partials/date_selection.htm' %}
          
	</div>
 	 <ul class="pager">
   
   
 		<li class="previous pointer">
 					 <a data-href="{% url 'customer:service_selection_appointment' %}?dealer_code={{dealer_code}}&appointment_id={{appointment.id}}&accordion=repairs" >
 						<span aria-hidden="true">←</span> Previous</a>
 						</li>
   		<li class="next pointer" id="submit_btn">
   				<a data-href="{% url 'customer:book_appointment' %}?dealer_code={{dealer_code}}&appointment_id={{appointment.id}}">
   				
   				Next <span aria-hidden="true">→</span></a>
   		</li>
  	</ul>
{% endblock %}
{% block js %}
{{block.super}}
 
		<script src="{% static "customer/js/settings.js" %}"></script>
		<script src="{% static "customer/js/vehicle_selection.js" %}"></script>
		<script src="{% static "customer/js/snapshot.js" %}"></script>
		<script src="{% static "customer/js/bootstrap_dialog.js" %}"></script>
		<link rel="stylesheet" href="{% static "customer/css/settings_login.css" %}" />
		<script>
		var url_appt_update_time_template = "{% url 'dealership:appointment_update_time' %}";
		var url_appointment_create_update = "{% url 'dealership:appointment_create_update' %}";
		var url_appointment_wayaway_save = "{% url 'dealership:appointment_wayaway_save'%}";
		var url_appointment_wayaway = "{% url 'dealership:appointment_wayaway'%}";
		var url_appointment_account_info = "{% url 'dealership:appointment_accountinfo'%}";
 	
 	
 	
		$(document).ready(function(){
			var accordion = "{{accordion}}"
			if(accordion=="advisor" || accordion ==""){
				openContainer($("#advisor_selection_from"));
			}
			else if(accordion == "wayaway"){
				openContainer($("#wayaway_selection_form"));
			}else if(accordion == "date"){
				openContainer($("#date_selection_form"));
			}
			
			
			$("body").on("click",".next",function(){
				if($("#advisor_selection_from").find(".collapsable_div").css("display")=="block"){
					openContainer($("#wayaway_selection_form"));
				}else if($("#wayaway_selection_form").find(".collapsable_div").css("display")=="block"){
					var way_away_len = $(".wayaway-btn").find(".glyphicon-ok").length
					if (way_away_len ==0){
						BootstrapDialog.show({
				            title: 'Error',
				            message: 'Please select a wayaway'
				        });
					}
					else{
						openContainer($("#date_selection_form"));
					}
				}else{
					if($("body").find(".start-time.btn-success").length == 0){
						BootstrapDialog.show({
				            title: 'Error',
				            message: 'Please select a datetime'
				        });
					}else{
						window.location = $(this).find("a").data("href");
					}
					
					
				}
			});
			
			$("body").on("click",".previous",function(){
				if($("#date_selection_form").find(".collapsable_div").css("display")=="block"){
					openContainer($("#wayaway_selection_form"));
				}
				else if($("#wayaway_selection_form").find(".collapsable_div").css("display")=="block"){
					openContainer($("#advisor_selection_from"));
				}else {
					window.location = $(this).find("a").data("href");
				}
			});
			
			var search = "";
			var criteria = "";
			var panel = "{{ qstring.panel }}";
			var cust_id = 12;
			var appt_id = {{appointment.id}};
			
			window.dealershipAppointment = new DealershipAppointment();
			var panel_id = "#date-appointment";
	    	 window.dealershipAppointment.switchAccordian(panel_id);
	    	window.dealershipAppointment.save_time_on_selection =  true;
	      	window.dealershipAppointment.
	      	getTimeForAppointment(url_appt_update_time_template, appt_id,
	      			{'panel_id':panel_id, 'callback':window.dealershipAppointment.saveAppointmentTime});
				      
	      	window.dealershipAppointment.date_save_callback	 = 	resetadvisor;
	      	
	      	var advisor_selection = new AdvisorSelection();
			advisor_selection.panel = "#advisor-appointment";
			advisor_selection.dealer_code = "{{dealer_code}}"
			advisor_selection.pagination_container = "#advisor_pagination"
			advisor_selection.appointment_id = "{{appointment.id}}"
			advisor_selection.select_listener = advisor_selection.selectAdvisor;
			advisor_selection.advisor_fetch_url = "{% url 'customer:get_all_advisors_ajax'%}"
			advisor_selection.advisor_save_url = "{% url 'customer:save_advisor_ajax'%}"
			advisor_selection.setAdvisors();
			advisor_selection.save_success_callback = reload_timegrid;
			advisor_selection.default_image = "noimage.gif";
			
			/* way away start*/
			var dealershipAppointment= new DealershipAppointment();
 			var appt_id = {{appointment.id}}
 			var panel_id_wy = "#wayaway-appointment";
	    	var panelObject = {'cust_id':0, 'panel_id':panel_id_wy,"dealer_code":"{{dealer_code}}" ,
	    			'callback':wayawaycallback};
	    	{%if appointment.customer %}
	    		panelObject.cust_id = {{appointment.customer.id}}
	    	{%endif%}
	        dealershipAppointment.getWayAwayForAppointment(url_appointment_wayaway, appt_id, panelObject);
	     
	        
	        
			function wayawaycallback(param1,param2){
	        	dealershipAppointment.saveWayAwayForAppointmentCallback(param1,param2)
	        	fillrollup()
	        }
	        
	        
			function resetadvisor(param1,param2){
				advisor_selection.setAdvisors()
				fillrollup()
			}
			
			function reload_timegrid(){
				
				window.dealershipAppointment.
		      	getTimeForAppointment(url_appt_update_time_template, appt_id,
		      			{'panel_id':panel_id, 'callback':window.dealershipAppointment.saveAppointmentTime});
				fillrollup()
			}
			
			function fillrollup(){
				
				var dt_len = $("#date-appointment").find(".btn-success").length;
				var way_away_len = $(".wayaway-btn").find(".glyphicon-ok").length
				if(advisor_selection.selected_advisor_id != null || dt_len > 0 ||way_away_len >0   ){
					console.info(advisor_selection.selected_advisor_id)
					var text= "";
					if(advisor_selection.selected_advisor_id!=null ){
						text += "Advisor"
					}
					if(dt_len > 0 ){
						if(text!=""){
							text+=", "
						}
						text += "Date"
					}
					if(way_away_len > 0 ){
						if(text!=""){
							text+=", "
						}
						text += "Way Away"
					}
					text += " selected";
					$("#date_adv_top_bar").html(text)
					
				}
			}
		})
		
		</script>
		
	{% endblock%}
	{% block extra %}
	
{%endblock%}